// Generated by scripts/build_site_candidate_data.py. Do not edit directly.
export const candidateSources = [
  {
    "id": "B3S0027",
    "title": "2023年度新人戦 日本体育大学プロフィール",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/5/type/rookie/y/2023/s/men",
    "location": "日本体育大学 PROFILE > 学生コーチ / 日本体育大学 PROFILE > 学生コーチ > 本松龍斗",
    "accessedAt": "2026-09-20",
    "dataStatus": "candidate"
  },
  {
    "id": "B3S0028",
    "title": "第76回インカレ 日本体育大学プロフィール",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/5/type/intercollege/y/2024/s/men",
    "location": "日本体育大学 PROFILE > 学生コーチ > 本松龍斗",
    "accessedAt": "2026-09-20",
    "dataStatus": "candidate"
  },
  {
    "id": "SRC000013",
    "title": "ボックススコア：福岡第一 vs 県立四日市工業",
    "publisher": "日本バスケットボール協会（JBA）",
    "url": "https://wintercup2020.japanbasketball.jp/boxscore/?period=18&schedulekey=6898",
    "location": "福岡第一ボックススコア > No.31 / 福岡第一ボックススコア > No.27 / 福岡第一ボックススコア > No.23",
    "accessedAt": "2026-09-19",
    "dataStatus": "candidate"
  },
  {
    "id": "SRC000023",
    "title": "2021年度新入生紹介③ : CHUO BASKETBALL",
    "publisher": "中央大学学友会体育連盟バスケットボール部",
    "url": "http://blog.livedoor.jp/chuo_basket/archives/55638062.html",
    "location": "2021年度新入生紹介③ > #7 松本宗志 / 2021年度新入生紹介③ > ポジションG / ページ名と公開日 > 2021年度新入生紹介",
    "accessedAt": "2026-09-19",
    "dataStatus": "candidate"
  },
  {
    "id": "SRC-CAND-B001-001",
    "title": "福岡第一高校 第96回天皇杯出場チーム",
    "publisher": "日本バスケットボール協会（JBA）",
    "url": "https://zennihon2020-21.japanbasketball.jp/team/1st/men-fukuoka",
    "location": "TEAM DATA > マネージャー / 福岡第一高校 > TEAM DATA",
    "accessedAt": "2026-09-19",
    "dataStatus": "candidate"
  }
] as const;

export const candidatePlayers = [
  {
    "id": "P000016",
    "slug": "p000016",
    "name": "本松 龍斗",
    "cardContext": "期間未確認 · 日本体育大学",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [],
    "careers": [
      {
        "id": "C000033",
        "period": "期間未確認",
        "organization": "日本体育大学",
        "organizationId": "ORG000020",
        "detail": "Student Coach",
        "status": "candidate",
        "sourceIds": [
          "B3S0027",
          "B3S0028"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000011",
    "slug": "p000011",
    "name": "砂川 琉勇",
    "cardContext": "期間未確認 · 福岡第一高等学校",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [],
    "careers": [
      {
        "id": "C000011",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "SRC000013"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000013",
    "slug": "p000013",
    "name": "松本 宗志",
    "cardContext": "期間未確認 · 福岡第一高等学校",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [],
    "careers": [
      {
        "id": "C000013",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "SRC000013"
        ]
      },
      {
        "id": "C000029",
        "period": "2021年〜",
        "organization": "中央大学",
        "organizationId": "ORG000016",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "SRC000023"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000017",
    "slug": "p000017",
    "name": "泉美 優知",
    "cardContext": "期間未確認 · 福岡第一高等学校",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [],
    "careers": [
      {
        "id": "C000017",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "Manager",
        "status": "candidate",
        "sourceIds": [
          "SRC-CAND-B001-001"
        ]
      }
    ],
    "aliases": []
  }
] as const;
