// Generated by scripts/build_site_candidate_data.py. Do not edit directly.
export const candidateSources = [
  {
    "id": "B3S0027",
    "title": "2023年度新人戦 日本体育大学プロフィール",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/5/type/rookie/y/2023/s/men",
    "location": "日本体育大学 PROFILE > 学生コーチ / 日本体育大学 PROFILE > 学生コーチ > 本松龍斗",
    "accessedAt": "2026-09-20",
    "dataStatus": "candidate"
  },
  {
    "id": "B3S0028",
    "title": "第76回インカレ 日本体育大学プロフィール",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/5/type/intercollege/y/2024/s/men",
    "location": "日本体育大学 PROFILE > 学生コーチ > 本松龍斗",
    "accessedAt": "2026-09-20",
    "dataStatus": "candidate"
  },
  {
    "id": "SRC000013",
    "title": "ボックススコア：福岡第一 vs 県立四日市工業",
    "publisher": "日本バスケットボール協会（JBA）",
    "url": "https://wintercup2020.japanbasketball.jp/boxscore/?period=18&schedulekey=6898",
    "location": "福岡第一ボックススコア > No.31 / 福岡第一ボックススコア > No.27 / 福岡第一ボックススコア > No.23",
    "accessedAt": "2026-09-19",
    "dataStatus": "candidate"
  },
  {
    "id": "SRC000023",
    "title": "2021年度新入生紹介③ : CHUO BASKETBALL",
    "publisher": "中央大学学友会体育連盟バスケットボール部",
    "url": "http://blog.livedoor.jp/chuo_basket/archives/55638062.html",
    "location": "2021年度新入生紹介③ > #7 松本宗志 / 2021年度新入生紹介③ > ポジションG / ページ名と公開日 > 2021年度新入生紹介",
    "accessedAt": "2026-09-19",
    "dataStatus": "candidate"
  },
  {
    "id": "SRC-CAND-B001-001",
    "title": "福岡第一高校 第96回天皇杯出場チーム",
    "publisher": "日本バスケットボール協会（JBA）",
    "url": "https://zennihon2020-21.japanbasketball.jp/team/1st/men-fukuoka",
    "location": "TEAM DATA > マネージャー / 福岡第一高校 > TEAM DATA",
    "accessedAt": "2026-09-19",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0012",
    "title": "第70回全日本大学バスケットボール選手権 東海大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/44/type/intercollege/y/2018/s/men",
    "location": "東海大学ROSTER > No.37 秋山皓太 / ROSTER > 4年・大会年2018",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0003",
    "title": "秋山皓太 選手情報",
    "publisher": "B3リーグ",
    "url": "https://www.b3league.jp/player/?key=86&player=22402&team=2727",
    "location": "選手情報 > 英語表記 / 選手情報 > 出身校 / 選手情報 > 立川ダイス / PLAYER STATS > 50試合 / PLAYER STATS / 選手情報 > 所属クラブ",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0002",
    "title": "平成26年度男子U-18日本代表チーム候補選手メンバー表",
    "publisher": "日本バスケットボール協会",
    "url": "https://www.japanbasketball.jp/wp/wp-content/uploads/jba2014020-2.pdf",
    "location": "PDF 選手表 > No.28 / PDF 選手表 > No.28 > 生年月日 / PDF 選手表 > No.28 > 所属 / PDF 注記 > 所属・年齢基準日",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0005",
    "title": "大城侑朔 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=10854",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / 基本情報 > 出身校 / クラブ所属履歴 > 2017-18〜2025-26 八王子 / 2024-25 B3RS シーズン成績 / クラブ所属履歴 > 2017-18 八王子 / クラブ所属履歴 > 2025-26 八王子 / シーズン成績 > 2024-25 / クラブ所属履歴 > 八王子",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0004",
    "title": "平成23年度男子U-16日本代表候補選手 参加メンバー表",
    "publisher": "日本バスケットボール協会",
    "url": "https://www.japanbasketball.jp/wp-content/uploads/2ecfbc3e55987cf0d0eee45695bc35cf.pdf",
    "location": "PDF 選手表 > 大城侑朔 > 生年月日 / PDF 選手表 > 大城侑朔 > 所属 / PDF 選手表 > 大城侑朔 / PDF 注記 > 所属・年齢基準日",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0013",
    "title": "第67回全日本大学バスケットボール選手権 日本体育大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/5/type/intercollege/y/2015/s/men",
    "location": "日本体育大学ROSTER > No.14 大城侑朔 / ROSTER > 3年・大会年2015",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0006",
    "title": "第71回全日本大学バスケットボール選手権 日本体育大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/5/type/intercollege/y/2019/s/men",
    "location": "日本体育大学ROSTER > No.24 > 出身校 / 日本体育大学ROSTER > No.24 / ROSTER > No.24 > SF / 第71回インカレROSTER > 3年 / 出場校 > 日本体育大学",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0007",
    "title": "土居光 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=36863",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / 基本情報 > 生年月日 / クラブ所属履歴 > 2025-26 東京Z / 2025-26 B3RS シーズン成績 / 2025-26シーズン終了時 / シーズン成績 > 2025-26 / クラブ所属履歴 > 東京Z",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0009",
    "title": "松本礼太 B3所属選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=49711",
    "location": "クラブ所属履歴 > 2025-26 徳島 / 2025-26シーズン終了時",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0001",
    "title": "福岡第一高等学校 学校案内2022",
    "publisher": "福岡第一高等学校",
    "url": "https://f.f-parama.ed.jp/wp-content/uploads/2022/01/panf2022.pdf",
    "location": "学校案内 > Bリーグ所属卒業生 > 松本礼太 / 学校案内表紙・発行元",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0010",
    "title": "徳島ガンバロウズ 2025-26チーム成績",
    "publisher": "B3リーグ",
    "url": "https://www.b3league.jp/club/tokushima/",
    "location": "徳島ガンバロウズ > No.12 / チーム成績 > No.12 松本礼太 / チーム名",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0014",
    "title": "第73回全日本大学バスケットボール選手権 東海大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/44/type/intercollege/y/2021/s/men",
    "location": "東海大学ROSTER > No.31 松本礼太 / ROSTER > 4年・大会年2021",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0008",
    "title": "松本礼太 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=51000138",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / 基本情報 > 生年月日 / 基本情報 > 出身校",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0037",
    "title": "中学日本一を実現した親子鷹 小4から「別格」だった富樫勇樹",
    "publisher": "Yahoo!スポーツ（スポーツナビ）",
    "url": "https://sports.yahoo.co.jp/column/detail/202009170002-spnavi",
    "location": "本文 > 「本丸中学校（新潟県新発田市立）」に在籍、中3時に全中初優勝 / 本文 > 「中学卒業と同時にアメリカへ渡りました」",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0027",
    "title": "富樫 勇樹｜指揮官の信頼も厚い男子日本代表キャプテン",
    "publisher": "日本バスケットボール協会(JBA)",
    "url": "https://okinawa-basketball.japanbasketball.jp/column/2023/08/785",
    "location": "本文 > 渡米しワシントンDC郊外にあるモントロス・クリスチャン高校へ進学した",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0038",
    "title": "開志国際の富樫英樹コーチが語るバスケ愛と選手育成（前編）「勇樹は他の子とは全然違っていました」",
    "publisher": "BASKET COUNT",
    "url": "https://basket-count.com/article/detail/45530",
    "location": "本文 > 富樫英樹コーチが「51歳の年に開志国際ができるということで高校に移った」、開志国際は2018年にインターハイ初優勝（就任5年後）",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0001",
    "title": "富樫勇樹 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=9055",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / 基本情報 > 生年月日 / プロフィール > 出身校（高） / クラブ所属履歴 > 2026-27シーズン 千葉J",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0026",
    "title": "富樫勇樹 - Wikipedia",
    "publisher": "Wikipedia",
    "url": "https://ja.wikipedia.org/wiki/富樫勇樹",
    "location": "本文 > モントローズ・クリスチャン高校に進学 / 本文 > 9月28日にNBLの千葉ジェッツとの契約合意が発表 / 本文 > アーリーエントリー制度を用いて秋田ノーザンハピネッツに入団 / 本文 > 秋田ノーザンハピネッツ（2012年12月〜2014年6月） / 本文 > テキサス・レジェンズ（NBA傘下Dリーグ、2014年11月〜2015年2月） / 本文 > 2014年秋に契約し、11月17日に到着 / 本文 > 2月の足首捻挫後は回復が思わしくなかった / 経歴 > 新発田市立本丸中学校でミニバスから育ち、中学3年時に全国大会で優勝 / 経歴 > バスケットボール部に所属 / 経歴 > 中学卒業後にアメリカへ留学し、モントロス・クリスチャン高等学校（メリーランド州）に進学",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0002",
    "title": "比江島慎 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=8589",
    "location": "選手プロフィール > 選手名 / 選手プロフィール > 英語表記 / 選手プロフィール > 生年月日 / プロフィール > 出身校（高） / プロフィール > 出身校（大） / クラブ所属履歴 > 2026-27シーズン 宇都宮ブレックス",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0004",
    "title": "篠山竜青 川崎ブレイブサンダース公式選手プロフィール",
    "publisher": "川崎ブレイブサンダース",
    "url": "https://kawasaki-bravethunders.com/team/players/detail/id=8224?PlayerID=8484",
    "location": "選手プロフィール > 出身校",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0030",
    "title": "篠山竜青 - Wikipedia",
    "publisher": "Wikipedia",
    "url": "https://ja.wikipedia.org/wiki/篠山竜青",
    "location": "本文 > 出身高校：北陸高等学校 / 本文 > 大学卒業後の2011年より東芝ブレイブサンダースに加入",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0003",
    "title": "篠山竜青 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=8484",
    "location": "プロフィール > 選手名 / プロフィール > 英語表記 / プロフィール > 生年月日 / クラブ所属履歴 > 2026-27シーズン Kawasaki",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0008",
    "title": "五十嵐圭や篠山竜青など名ポイントガードを多数輩出…Bリーグで活躍する北陸高校OB",
    "publisher": "バスケットボールキング",
    "url": "https://basketballking.jp/news/japan/highschool/20200713/239606.html",
    "location": "本文 > 2004年に北陸に入学し / 本文 > 3年次のインターハイ優勝、ウインターカップベスト5",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0029",
    "title": "（２）バスケットボール部 齋藤拓実",
    "publisher": "明大スポーツ新聞部",
    "url": "https://meisupo.net/news/8783/",
    "location": "本文 > 2014年5月時点で1年生（営１）と明記",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0028",
    "title": "齋藤拓実 - Wikipedia",
    "publisher": "Wikipedia",
    "url": "https://ja.wikipedia.org/wiki/齋藤拓実",
    "location": "本文 > 桐光学園に進学",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0007",
    "title": "【トッププレーヤーの高校時代】齋藤拓実（前編）「父と兄の影響でバスケを始めた」",
    "publisher": "バスケットボールキング",
    "url": "https://basketballking.jp/news/japan/b1/20221126/403301.html",
    "location": "記事本文 > 桐光学園高校 / 記事本文 > 高校2年次にインターハイ・ウインターカップ出場",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0006",
    "title": "齋藤拓実 名古屋ダイヤモンドドルフィンズ公式選手プロフィール",
    "publisher": "名古屋ダイヤモンドドルフィンズ",
    "url": "https://nagoya-dolphins.jp/team/players/detail/id=14611?PlayerID=14301",
    "location": "選手プロフィール > 出身校",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0005",
    "title": "齋藤拓実 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=14301",
    "location": "選手プロフィール > 選手名 / 選手プロフィール > 英語表記 / 選手プロフィール > 生年月日 / クラブ所属履歴 > 2026-27シーズン 名古屋ダイヤモンドドルフィンズ / 出身校欄 > 桐光学園高等学校 / 経歴概要 > 明治大学を経て2017年にアルバルク東京でプロバスケットボール人生をスタート",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0032",
    "title": "田中大貴 (バスケットボール) - Wikipedia",
    "publisher": "Wikipedia",
    "url": "https://ja.wikipedia.org/wiki/田中大貴_(バスケットボール)",
    "location": "本文 > 2007年4月、長崎西高校に進学 / 本文 > 2010年4月、東海大学に進学 / 本文 > 4年生時は主将としてチームを牽引",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0009",
    "title": "田中大貴 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=9037",
    "location": "基本情報 > 選手名 / 基本情報 > 生年月日 / プロフィール > 出身校",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0010",
    "title": "田中大貴 東京サンロッカーズ公式選手プロフィール",
    "publisher": "東京サンロッカーズ",
    "url": "https://www.sunrockers.jp/team/players/detail/id=16564?PlayerID=9037",
    "location": "所属クラブの変遷 > 東京サンロッカーズ渋谷（2023-24シーズン以降現在）",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0011",
    "title": "ワタシノB.LEAGUE選手一覧 | 長崎県立長崎西高等学校",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/mybleague_list/?TagID=35:%E9%95%B7%E5%B4%8E%E7%9C%8C%E7%AB%8B%E9%95%B7%E5%B4%8E%E8%A5%BF%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1",
    "location": "検索結果 > 田中大貴",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0015",
    "title": "ワタシノB.LEAGUE選手一覧 | 沖縄県立北中城高等学校",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/mybleague_list/?TagID=35:%E6%B2%96%E7%B8%84%E7%9C%8C%E7%AB%8B%E5%8C%97%E4%B8%AD%E5%9F%8E%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1",
    "location": "検索結果：1人 > 岸本隆一",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0014",
    "title": "岸本 隆一選手 契約締結（複数年）のお知らせ",
    "publisher": "京都ハンナリーズ",
    "url": "https://hannaryz.jp/news/detail/id=24529",
    "location": "学歴 > 大東文化大学 / 契約期間 > 2026-27シーズンから2027-28シーズンまで、2年間の複数年契約",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0013",
    "title": "岸本隆一 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=8655",
    "location": "選手プロフィール > 選手名 / 選手プロフィール > 生年月日",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0031",
    "title": "西田優大 - Wikipedia",
    "publisher": "Wikipedia",
    "url": "https://ja.wikipedia.org/wiki/西田優大",
    "location": "本文 > 3年次が2019年12月 / 本文 > 4年次が2020年12月",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0017",
    "title": "西田優大 シーホース三河公式選手プロフィール",
    "publisher": "シーホース三河",
    "url": "https://go-seahorses.jp/team/players/detail/id=17209?PlayerID=30403",
    "location": "基本情報 > 選手名 / 基本情報 > 生年月日 / 経歴概要 > 高校で大濠高校に進学 / 経歴概要 > 大学では東海大学でプレー / 現在の所属チーム > シーホース三河",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0021",
    "title": "【トッププレーヤーの高校時代】金丸晃輔「バスケをはじめたきっかけは、ダイエット」（前編）",
    "publisher": "バスケットボールキング",
    "url": "https://basketballking.jp/news/japan/b1/20201124/298048.html",
    "location": "本文 > 高校進学時、大濠高校への進学を決定 / 本文 > 高校では1年生からメンバー入り",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0018",
    "title": "金丸晃輔 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=8592",
    "location": "基本情報 > 選手名 / 出身校欄 > 福岡大学附属大濠高等学校",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0020",
    "title": "プロバスケットボール選手・金丸晃輔さんにインタビュー【第1回】",
    "publisher": "Meiji NOW（明治大学）",
    "url": "https://meijinow.jp/senior/interview/8831",
    "location": "記事本文 > 2011年政治経済学部卒 / 記事冒頭 > 明大在学時にはバスケットボール部主将を務め / 本文 > 金丸 晃輔さん〈2011年政治経済学部卒〉",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0019",
    "title": "14 金丸晃輔選手 佐賀バルーナーズ公式選手プロフィール",
    "publisher": "佐賀バルーナーズ",
    "url": "https://ballooners.jp/team/member/player14",
    "location": "選手情報 > 生年月日 / 経歴 > 2024年～",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0022",
    "title": "安藤周人 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=10815",
    "location": "基本情報 > 選手名 / 基本情報 > 生年月日 / プロフィール > 出身校 / プロフィール > 大学 / 所属クラブの変遷 > アルバルク東京（現所属）",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0023",
    "title": "片岡大晴 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=8481",
    "location": "基本情報 > 選手名 / 基本情報 > 生年月日 / プロフィール > 出身校 / プロフィール > 大学 / 所属クラブの変遷 > 仙台89ERS（現所属、2026-27シーズン契約）",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0024",
    "title": "松脇圭志 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=30434",
    "location": "基本情報 > 選手名 / 基本情報 > 生年月日 / プロフィール > 出身校 / プロフィール > 大学 / 所属クラブの変遷 > 琉球ゴールデンキングス（現所属）",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0034",
    "title": "松脇圭志 - Wikipedia",
    "publisher": "Wikipedia",
    "url": "https://ja.wikipedia.org/wiki/松脇圭志",
    "location": "本文 > 4年次の2020年1月に富山グラウジーズへ特別指定選手として入団",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0025",
    "title": "星川堅信 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=5100000021",
    "location": "基本情報 > 選手名 / 基本情報 > 生年月日 / プロフィール > 出身校 / プロフィール > 大学 / 所属クラブの変遷 > 長崎ヴェルカ（現所属）",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0039",
    "title": "田口成浩 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=8468",
    "location": "基本情報 > 選手名 / 基本情報 > 生年月日 / プロフィール > 出身校（高）：明桜高等学校(現・ノースアジア大学明桜高等学校) / プロフィール > 出身校（高） / プロフィール > 出身校（大）：富士大学 / プロフィール > 出身校（大） / クラブ所属履歴 > 2026-27 秋田",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0040",
    "title": "竹内譲次 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=9033",
    "location": "基本情報 > 選手名 / 基本情報 > 生年月日 / Wikipedia > 経歴 > 出身高校：洛南高等学校 / 同上 / Wikipedia > 経歴 > 出身大学：東海大学 / クラブ所属履歴 > 2026-27 大阪（2021-22シーズンより継続） / クラブ所属履歴 > 2026-27 大阪",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0041",
    "title": "辻直人 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=8487",
    "location": "基本情報 > 選手名 / 基本情報 > 生年月日1989年9月8日 / Wikipedia > 経歴 > 出身高校：洛南高等学校 / 同上 / Wikipedia > 経歴 > 出身大学：青山学院大学 / クラブ所属履歴 > 2026-27 群馬（2023-24シーズンより継続） / クラブ所属履歴 > 2026-27 群馬",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0042",
    "title": "安藤誓哉 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=8467",
    "location": "基本情報 > 選手名 / 基本情報 > 生年月日1992年7月15日 / Wikipedia > 経歴 > 出身高校：明成高校（仙台大学附属明成高等学校） / 同上 / Wikipedia > 経歴 > 出身大学：明治大学 / クラブ所属履歴 > 2026-27 A千葉",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0043",
    "title": "水戸健史 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=8501",
    "location": "基本情報 > 選手名 / 基本情報 > 生年月日1985年4月23日 / プロフィール > 出身校（大）：近畿大学 / プロフィール > 出身校（大） / クラブ所属履歴 > 2026-27 富山（2016-17シーズンより継続） / クラブ所属履歴 > 2026-27 富山",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0044",
    "title": "古川孝敏 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=8500",
    "location": "基本情報 > 選手名 / 基本情報 > 生年月日1987年10月20日 / プロフィール > 出身校（大）：東海大学 / プロフィール > 出身校（大） / クラブ所属履歴 > 2026-27 信州",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0045",
    "title": "田原隆徳 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=10297",
    "location": "基本情報 > 選手名 / 基本情報 > 生年月日1994年4月25日 / プロフィール > 出身校（高）：北海道恵庭南高等学校 / プロフィール > 出身校（高） / プロフィール > 出身校（大）：札幌大学 / プロフィール > 出身校（大） / クラブ所属履歴 > 2026-27 滋賀（3年連続所属） / クラブ所属履歴 > 2026-27 滋賀",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0046",
    "title": "白濱僚祐 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=8734",
    "location": "基本情報 > 選手名 / 基本情報 > 生年月日1991年8月29日 / プロフィール > 出身校（高）：佐賀県立佐賀北高等学校 / プロフィール > 出身校（高） / プロフィール > 出身校（大）：白鴎大学 / プロフィール > 出身校（大） / クラブ所属履歴 > 2026-27 島根（2021-22シーズンより継続） / クラブ所属履歴 > 2026-27 島根",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0048",
    "title": "TOP TEAM｜千葉ジェッツふなばし",
    "publisher": "千葉ジェッツふなばし公式",
    "url": "https://chibajets.jp/team/",
    "location": "TOP TEAM選手一覧 > 渡邊雄太",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0047",
    "title": "渡邊雄太 選手情報",
    "publisher": "B.LEAGUE公式 (bleague.jp, PlayerID=51000428)",
    "url": "https://www.bleague.jp/player/51000428/",
    "location": "選手名 / 生年月日 > 1994年10月13日 / 出身校 > 尽誠学園高等学校 / 出身校 > ジョージ・ワシントン大学 / クラブ所属履歴 > 2026-27 千葉J",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0049",
    "title": "八村塁",
    "publisher": "Wikipedia日本語版",
    "url": "https://ja.wikipedia.org/wiki/八村塁",
    "location": "冒頭 / 基本情報 > 1998年2月8日生まれ / 経歴 > 出身高校：明成高等学校（宮城県） / 経歴 > ゴンザガ大学に進学",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0050",
    "title": "八村塁、新天地はクリッパーズ！ NBA3チーム目、2年契約と現地報道",
    "publisher": "バスケットボールキング (basketballking.jp)",
    "url": "https://basketballking.jp/news/world/20260707/622623.html",
    "location": "本文 > 「発表日：2026年7月7日（現地時間6日）」「移籍前の所属：ロサンゼルス・レイカーズ」、ロサンゼルス・クリッパーズと2年契約",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0051",
    "title": "田臥勇太 選手情報",
    "publisher": "B.LEAGUE公式 (bleague.jp, PlayerID=8650)",
    "url": "https://www.bleague.jp/player/8650/",
    "location": "選手名 / 生年月日 > 1980年10月5日 / 出身校 > 秋田県立能代工業高等学校（現・秋田県立能代科学技術高等学校） / 出身校 > ブリガムヤング大学ハワイ校 / クラブ所属履歴 > 2026-27シーズン：宇都宮ブレックス（2023-24シーズン以降、継続して宇都宮ブレックス）",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0052",
    "title": "富永啓生 選手情報",
    "publisher": "B.LEAGUE公式 (bleague.jp, PlayerID=19755)",
    "url": "https://www.bleague.jp/player/19755/",
    "location": "選手名 / 生年月日 > 2001年2月1日 / 出身校 > 桜丘高等学校 / 出身校 > ネブラスカ大学 / クラブ所属履歴 > 2026-27 北海道 / 2025-26 北海道",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  }
] as const;

export const candidatePlayers = [
  {
    "id": "P000016",
    "slug": "p000016",
    "name": "本松 龍斗",
    "cardContext": "期間未確認 · 日本体育大学",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [],
    "careers": [
      {
        "id": "C000033",
        "period": "期間未確認",
        "organization": "日本体育大学",
        "organizationId": "ORG000020",
        "detail": "Student Coach",
        "status": "candidate",
        "sourceIds": [
          "B3S0027",
          "B3S0028"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000011",
    "slug": "p000011",
    "name": "砂川 琉勇",
    "cardContext": "期間未確認 · 福岡第一高等学校",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [],
    "careers": [
      {
        "id": "C000011",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "SRC000013"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000013",
    "slug": "p000013",
    "name": "松本 宗志",
    "cardContext": "期間未確認 · 福岡第一高等学校",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [],
    "careers": [
      {
        "id": "C000013",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "SRC000013"
        ]
      },
      {
        "id": "C000029",
        "period": "2021年〜",
        "organization": "中央大学",
        "organizationId": "ORG000016",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "SRC000023"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000017",
    "slug": "p000017",
    "name": "泉美 優知",
    "cardContext": "期間未確認 · 福岡第一高等学校",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [],
    "careers": [
      {
        "id": "C000017",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "Manager",
        "status": "candidate",
        "sourceIds": [
          "SRC-CAND-B001-001"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000079",
    "slug": "p000079",
    "name": "秋山 皓太",
    "cardContext": "期間未確認 · 立川ダイス",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "英字表記",
        "value": "Kota Akiyama",
        "context": "B3公式表記",
        "sourceIds": [
          "B6W2S0003"
        ]
      },
      {
        "label": "生年月日",
        "value": "1996年12月29日",
        "context": "JBA公式生年月日",
        "sourceIds": [
          "B6W2S0002"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000278",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0002"
        ]
      },
      {
        "id": "C000279",
        "period": "期間未確認",
        "organization": "東海大学",
        "organizationId": "ORG000015",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0003",
          "B6W2S0012"
        ]
      },
      {
        "id": "C000280",
        "period": "期間未確認",
        "organization": "立川ダイス",
        "organizationId": "ORG000115",
        "detail": "選手 · 公式戦記録：B3公式戦50試合",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0003"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000080",
    "slug": "p000080",
    "name": "大城 侑朔",
    "cardContext": "期間未確認 · 日本体育大学",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "英字表記",
        "value": "Yusaku Oshiro",
        "context": "B.LEAGUE公式表記",
        "sourceIds": [
          "B6W2S0005"
        ]
      },
      {
        "label": "生年月日",
        "value": "1995年3月1日",
        "context": "JBA公式生年月日",
        "sourceIds": [
          "B6W2S0004"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000281",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0004"
        ]
      },
      {
        "id": "C000282",
        "period": "期間未確認",
        "organization": "日本体育大学",
        "organizationId": "ORG000020",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0005",
          "B6W2S0013"
        ]
      },
      {
        "id": "C000283",
        "period": "2017–2026年",
        "organization": "東京八王子ビートレインズ",
        "organizationId": "ORG000111",
        "detail": "選手 · 公式戦記録：2024-25 B3RS 49試合",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0005"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000081",
    "slug": "p000081",
    "name": "土居 光",
    "cardContext": "期間未確認 · 日本体育大学",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "英字表記",
        "value": "Hikaru Doi",
        "context": "B.LEAGUE公式表記",
        "sourceIds": [
          "B6W2S0007"
        ]
      },
      {
        "label": "生年月日",
        "value": "1998年10月2日",
        "context": "B.LEAGUE公式生年月日",
        "sourceIds": [
          "B6W2S0007"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000284",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "所属を公式資料で確認",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0006"
        ]
      },
      {
        "id": "C000285",
        "period": "期間未確認",
        "organization": "日本体育大学",
        "organizationId": "ORG000020",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0006"
        ]
      },
      {
        "id": "C000286",
        "period": "2025–2026年",
        "organization": "アースフレンズ東京Z",
        "organizationId": "ORG000046",
        "detail": "選手 · 公式戦記録：2025-26 B3RS 23試合",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0007"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000082",
    "slug": "p000082",
    "name": "松本 礼太",
    "cardContext": "期間未確認 · 東海大学",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "英字表記",
        "value": "Reita Matsumoto",
        "context": "B.LEAGUE公式表記",
        "sourceIds": [
          "B6W2S0008"
        ]
      },
      {
        "label": "生年月日",
        "value": "1999年9月18日",
        "context": "B.LEAGUE公式生年月日",
        "sourceIds": [
          "B6W2S0008"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000287",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "所属を公式資料で確認",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0001"
        ]
      },
      {
        "id": "C000288",
        "period": "期間未確認",
        "organization": "東海大学",
        "organizationId": "ORG000015",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0008",
          "B6W2S0014"
        ]
      },
      {
        "id": "C000289",
        "period": "2025–2026年",
        "organization": "徳島ガンバロウズ",
        "organizationId": "ORG000116",
        "detail": "選手 · 公式戦記録：2025-26 B3公式戦30試合",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0009",
          "B6W2S0010"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000083",
    "slug": "p000083",
    "name": "富樫勇樹",
    "cardContext": "期間未確認 · 新発田市立本丸中学校",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "英字表記",
        "value": "Yuki Togashi",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B7S0001"
        ]
      },
      {
        "label": "生年月日",
        "value": "1993年7月30日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0001"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000299",
        "period": "期間未確認",
        "organization": "モントロス・クリスチャン高等学校",
        "organizationId": "ORG000117",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0001",
          "B7S0026",
          "B7S0027",
          "B7S0037",
          "B7S0038"
        ]
      },
      {
        "id": "C000300",
        "period": "2015年〜",
        "organization": "千葉ジェッツ",
        "organizationId": "ORG000118",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0001",
          "B7S0026"
        ]
      },
      {
        "id": "C000325",
        "period": "2012–2014年",
        "organization": "秋田ノーザンハピネッツ",
        "organizationId": "ORG000137",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0026"
        ]
      },
      {
        "id": "C000326",
        "period": "2014–2015年",
        "organization": "テキサス・レジェンズ",
        "organizationId": "ORG000138",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0026"
        ]
      },
      {
        "id": "C000330",
        "period": "期間未確認",
        "organization": "新発田市立本丸中学校",
        "organizationId": "ORG000141",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0026",
          "B7S0037"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000084",
    "slug": "p000084",
    "name": "比江島慎",
    "cardContext": "期間未確認 · 宇都宮ブレックス",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "英字表記",
        "value": "Makoto Hiejima",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B7S0002"
        ]
      },
      {
        "label": "生年月日",
        "value": "1990年8月11日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0002"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000290",
        "period": "期間未確認",
        "organization": "洛南高等学校",
        "organizationId": "ORG000119",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0002"
        ]
      },
      {
        "id": "C000291",
        "period": "期間未確認",
        "organization": "青山学院大学",
        "organizationId": "ORG000030",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0002"
        ]
      },
      {
        "id": "C000292",
        "period": "期間未確認",
        "organization": "宇都宮ブレックス",
        "organizationId": "ORG000047",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0002"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000085",
    "slug": "p000085",
    "name": "篠山竜青",
    "cardContext": "期間未確認 · 川崎ブレイブサンダース",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "英字表記",
        "value": "Ryusei Shinoyama",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B7S0003"
        ]
      },
      {
        "label": "生年月日",
        "value": "1988年7月20日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0003"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000296",
        "period": "2004年〜",
        "organization": "北陸高等学校",
        "organizationId": "ORG000120",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0008",
          "B7S0030"
        ]
      },
      {
        "id": "C000297",
        "period": "〜2011年",
        "organization": "日本大学",
        "organizationId": "ORG000121",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0004",
          "B7S0030"
        ]
      },
      {
        "id": "C000298",
        "period": "期間未確認",
        "organization": "川崎ブレイブサンダース",
        "organizationId": "ORG000122",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0003"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000086",
    "slug": "p000086",
    "name": "齋藤拓実",
    "cardContext": "期間未確認 · 名古屋ダイヤモンドドルフィンズ",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "英字表記",
        "value": "Takumi Saito",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B7S0005"
        ]
      },
      {
        "label": "生年月日",
        "value": "1995年8月11日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0005"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000293",
        "period": "〜2014年",
        "organization": "桐光学園高校",
        "organizationId": "ORG000123",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0007",
          "B7S0005",
          "B7S0028",
          "B7S0029"
        ]
      },
      {
        "id": "C000294",
        "period": "2014年〜",
        "organization": "明治大学",
        "organizationId": "ORG000124",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0006",
          "B7S0029"
        ]
      },
      {
        "id": "C000295",
        "period": "期間未確認",
        "organization": "名古屋ダイヤモンドドルフィンズ",
        "organizationId": "ORG000054",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0005"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000087",
    "slug": "p000087",
    "name": "田中大貴",
    "cardContext": "期間未確認 · 東京サンロッカーズ",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1991年9月3日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0009"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000301",
        "period": "2007–2010年",
        "organization": "長崎県立長崎西高等学校",
        "organizationId": "ORG000125",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0011",
          "B7S0032"
        ]
      },
      {
        "id": "C000302",
        "period": "2010–2014年",
        "organization": "東海大学",
        "organizationId": "ORG000015",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0009",
          "B7S0032"
        ]
      },
      {
        "id": "C000303",
        "period": "期間未確認",
        "organization": "東京サンロッカーズ",
        "organizationId": "ORG000114",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0010"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000088",
    "slug": "p000088",
    "name": "岸本隆一",
    "cardContext": "期間未確認 · 京都ハンナリーズ",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1990年5月17日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0013"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000304",
        "period": "期間未確認",
        "organization": "沖縄県立北中城高等学校",
        "organizationId": "ORG000126",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0015"
        ]
      },
      {
        "id": "C000305",
        "period": "期間未確認",
        "organization": "大東文化大学",
        "organizationId": "ORG000128",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0014"
        ]
      },
      {
        "id": "C000306",
        "period": "期間未確認",
        "organization": "京都ハンナリーズ",
        "organizationId": "ORG000042",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0014"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000089",
    "slug": "p000089",
    "name": "西田優大",
    "cardContext": "期間未確認 · シーホース三河",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1999年3月13日",
        "context": "クラブ公式の生年月日",
        "sourceIds": [
          "B7S0017"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000307",
        "period": "期間未確認",
        "organization": "福岡大学附属大濠高等学校",
        "organizationId": "ORG000127",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0017"
        ]
      },
      {
        "id": "C000308",
        "period": "2017–2021年",
        "organization": "東海大学",
        "organizationId": "ORG000015",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0017",
          "B7S0031"
        ]
      },
      {
        "id": "C000309",
        "period": "期間未確認",
        "organization": "シーホース三河",
        "organizationId": "ORG000130",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0017"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000090",
    "slug": "p000090",
    "name": "金丸晃輔",
    "cardContext": "期間未確認 · 佐賀バルーナーズ",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1989年3月8日",
        "context": "クラブ公式の生年月日",
        "sourceIds": [
          "B7S0019"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000310",
        "period": "期間未確認",
        "organization": "福岡大学附属大濠高等学校",
        "organizationId": "ORG000127",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0021",
          "B7S0018"
        ]
      },
      {
        "id": "C000311",
        "period": "〜2011年",
        "organization": "明治大学",
        "organizationId": "ORG000124",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0020"
        ]
      },
      {
        "id": "C000312",
        "period": "期間未確認",
        "organization": "佐賀バルーナーズ",
        "organizationId": "ORG000048",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0019"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000091",
    "slug": "p000091",
    "name": "安藤周人",
    "cardContext": "期間未確認 · アルバルク東京",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1994年6月13日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0022"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000313",
        "period": "期間未確認",
        "organization": "三重県立四日市工業高等学校",
        "organizationId": "ORG000131",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0022"
        ]
      },
      {
        "id": "C000314",
        "period": "期間未確認",
        "organization": "青山学院大学",
        "organizationId": "ORG000030",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0022"
        ]
      },
      {
        "id": "C000315",
        "period": "期間未確認",
        "organization": "アルバルク東京",
        "organizationId": "ORG000109",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0022"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000092",
    "slug": "p000092",
    "name": "片岡大晴",
    "cardContext": "期間未確認 · 仙台89ERS",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1985年12月24日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0023"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000316",
        "period": "期間未確認",
        "organization": "仙台市立仙台高等学校",
        "organizationId": "ORG000133",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0023"
        ]
      },
      {
        "id": "C000317",
        "period": "期間未確認",
        "organization": "白鷗大学",
        "organizationId": "ORG000093",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0023"
        ]
      },
      {
        "id": "C000318",
        "period": "期間未確認",
        "organization": "仙台89ERS",
        "organizationId": "ORG000132",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0023"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000093",
    "slug": "p000093",
    "name": "松脇圭志",
    "cardContext": "期間未確認 · 琉球ゴールデンキングス",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1997年5月15日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0024"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000319",
        "period": "期間未確認",
        "organization": "土浦日本大学高等学校",
        "organizationId": "ORG000134",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0024"
        ]
      },
      {
        "id": "C000320",
        "period": "〜2020年",
        "organization": "日本大学",
        "organizationId": "ORG000121",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0024",
          "B7S0034"
        ]
      },
      {
        "id": "C000321",
        "period": "期間未確認",
        "organization": "琉球ゴールデンキングス",
        "organizationId": "ORG000106",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0024"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000094",
    "slug": "p000094",
    "name": "星川堅信",
    "cardContext": "期間未確認 · 長崎ヴェルカ",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "2001年11月1日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0025"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000322",
        "period": "期間未確認",
        "organization": "洛南高等学校",
        "organizationId": "ORG000119",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0025"
        ]
      },
      {
        "id": "C000323",
        "period": "期間未確認",
        "organization": "早稲田大学",
        "organizationId": "ORG000136",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0025"
        ]
      },
      {
        "id": "C000324",
        "period": "期間未確認",
        "organization": "長崎ヴェルカ",
        "organizationId": "ORG000135",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0025"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000095",
    "slug": "p000095",
    "name": "田口成浩",
    "cardContext": "期間未確認 · 秋田ノーザンハピネッツ",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1990年3月25日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0039"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000331",
        "period": "期間未確認",
        "organization": "明桜高等学校",
        "organizationId": "ORG000146",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0039"
        ]
      },
      {
        "id": "C000332",
        "period": "期間未確認",
        "organization": "富士大学",
        "organizationId": "ORG000145",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0039"
        ]
      },
      {
        "id": "C000333",
        "period": "期間未確認",
        "organization": "秋田ノーザンハピネッツ",
        "organizationId": "ORG000137",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0039"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000096",
    "slug": "p000096",
    "name": "竹内譲次",
    "cardContext": "期間未確認 · 大阪エヴェッサ",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1985年1月29日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0040"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000334",
        "period": "期間未確認",
        "organization": "洛南高等学校",
        "organizationId": "ORG000119",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0040"
        ]
      },
      {
        "id": "C000335",
        "period": "期間未確認",
        "organization": "東海大学",
        "organizationId": "ORG000015",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0040"
        ]
      },
      {
        "id": "C000336",
        "period": "期間未確認",
        "organization": "大阪エヴェッサ",
        "organizationId": "ORG000142",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0040"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000097",
    "slug": "p000097",
    "name": "辻直人",
    "cardContext": "期間未確認 · 群馬クレインサンダーズ",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1989年9月8日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0041"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000337",
        "period": "期間未確認",
        "organization": "洛南高等学校",
        "organizationId": "ORG000119",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0041"
        ]
      },
      {
        "id": "C000338",
        "period": "期間未確認",
        "organization": "青山学院大学",
        "organizationId": "ORG000030",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0041"
        ]
      },
      {
        "id": "C000339",
        "period": "期間未確認",
        "organization": "群馬クレインサンダーズ",
        "organizationId": "ORG000143",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0041"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000098",
    "slug": "p000098",
    "name": "安藤誓哉",
    "cardContext": "期間未確認 · アルティーリ千葉",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1992年7月15日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0042"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000340",
        "period": "期間未確認",
        "organization": "明成高等学校",
        "organizationId": "ORG000147",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0042"
        ]
      },
      {
        "id": "C000341",
        "period": "期間未確認",
        "organization": "明治大学",
        "organizationId": "ORG000124",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0042"
        ]
      },
      {
        "id": "C000342",
        "period": "期間未確認",
        "organization": "アルティーリ千葉",
        "organizationId": "ORG000144",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0042"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000099",
    "slug": "p000099",
    "name": "水戸健史",
    "cardContext": "期間未確認 · 富山グラウジーズ",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1985年4月23日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0043"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000343",
        "period": "期間未確認",
        "organization": "近畿大学",
        "organizationId": "ORG000148",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0043"
        ]
      },
      {
        "id": "C000344",
        "period": "期間未確認",
        "organization": "富山グラウジーズ",
        "organizationId": "ORG000149",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0043"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000100",
    "slug": "p000100",
    "name": "古川孝敏",
    "cardContext": "期間未確認 · 信州ブレイブウォリアーズ",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1987年10月20日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0044"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000345",
        "period": "期間未確認",
        "organization": "東海大学",
        "organizationId": "ORG000015",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0044"
        ]
      },
      {
        "id": "C000346",
        "period": "期間未確認",
        "organization": "信州ブレイブウォリアーズ",
        "organizationId": "ORG000150",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0044"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000101",
    "slug": "p000101",
    "name": "田原隆徳",
    "cardContext": "期間未確認 · 滋賀レイクス",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1994年4月25日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0045"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000347",
        "period": "期間未確認",
        "organization": "北海道恵庭南高等学校",
        "organizationId": "ORG000151",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0045"
        ]
      },
      {
        "id": "C000348",
        "period": "期間未確認",
        "organization": "札幌大学",
        "organizationId": "ORG000152",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0045"
        ]
      },
      {
        "id": "C000349",
        "period": "期間未確認",
        "organization": "滋賀レイクス",
        "organizationId": "ORG000153",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0045"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000102",
    "slug": "p000102",
    "name": "白濱僚祐",
    "cardContext": "期間未確認 · 島根スサノオマジック",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1991年8月29日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0046"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000350",
        "period": "期間未確認",
        "organization": "佐賀県立佐賀北高等学校",
        "organizationId": "ORG000154",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0046"
        ]
      },
      {
        "id": "C000351",
        "period": "期間未確認",
        "organization": "白鷗大学",
        "organizationId": "ORG000093",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0046"
        ]
      },
      {
        "id": "C000352",
        "period": "期間未確認",
        "organization": "島根スサノオマジック",
        "organizationId": "ORG000155",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0046"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000103",
    "slug": "p000103",
    "name": "渡邊雄太",
    "cardContext": "期間未確認 · 千葉ジェッツ",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [],
    "careers": [
      {
        "id": "C000353",
        "period": "期間未確認",
        "organization": "尽誠学園高等学校",
        "organizationId": "ORG000156",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0047"
        ]
      },
      {
        "id": "C000354",
        "period": "期間未確認",
        "organization": "ジョージ・ワシントン大学",
        "organizationId": "ORG000157",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0047"
        ]
      },
      {
        "id": "C000355",
        "period": "期間未確認",
        "organization": "千葉ジェッツ",
        "organizationId": "ORG000118",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0047",
          "B7S0048"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000104",
    "slug": "p000104",
    "name": "八村塁",
    "cardContext": "期間未確認 · ロサンゼルス・クリッパーズ",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [],
    "careers": [
      {
        "id": "C000356",
        "period": "期間未確認",
        "organization": "明成高等学校",
        "organizationId": "ORG000147",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0049"
        ]
      },
      {
        "id": "C000357",
        "period": "期間未確認",
        "organization": "ゴンザガ大学",
        "organizationId": "ORG000158",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0049"
        ]
      },
      {
        "id": "C000358",
        "period": "期間未確認",
        "organization": "ロサンゼルス・クリッパーズ",
        "organizationId": "ORG000140",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0050"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000105",
    "slug": "p000105",
    "name": "田臥勇太",
    "cardContext": "期間未確認 · 宇都宮ブレックス",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [],
    "careers": [
      {
        "id": "C000359",
        "period": "期間未確認",
        "organization": "秋田県立能代工業高等学校",
        "organizationId": "ORG000159",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0051"
        ]
      },
      {
        "id": "C000360",
        "period": "期間未確認",
        "organization": "ブリガムヤング大学ハワイ校",
        "organizationId": "ORG000160",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0051"
        ]
      },
      {
        "id": "C000361",
        "period": "期間未確認",
        "organization": "宇都宮ブレックス",
        "organizationId": "ORG000047",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0051"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000106",
    "slug": "p000106",
    "name": "富永啓生",
    "cardContext": "期間未確認 · レバンガ北海道",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [],
    "careers": [
      {
        "id": "C000362",
        "period": "期間未確認",
        "organization": "桜丘高等学校",
        "organizationId": "ORG000161",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0052"
        ]
      },
      {
        "id": "C000363",
        "period": "期間未確認",
        "organization": "ネブラスカ大学",
        "organizationId": "ORG000162",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0052"
        ]
      },
      {
        "id": "C000364",
        "period": "期間未確認",
        "organization": "レバンガ北海道",
        "organizationId": "ORG000092",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0052"
        ]
      }
    ],
    "aliases": []
  }
] as const;
