// Generated by scripts/build_site_candidate_data.py. Do not edit directly.
export const candidateSources = [
  {
    "id": "B3S0028",
    "title": "第76回インカレ 日本体育大学プロフィール",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/5/type/intercollege/y/2024/s/men",
    "location": "日本体育大学 PROFILE > 学生コーチ > 本松龍斗",
    "accessedAt": "2026-09-20",
    "dataStatus": "candidate"
  },
  {
    "id": "B3S0027",
    "title": "2023年度新人戦 日本体育大学プロフィール",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/5/type/rookie/y/2023/s/men",
    "location": "日本体育大学 PROFILE > 学生コーチ / 日本体育大学 PROFILE > 学生コーチ > 本松龍斗",
    "accessedAt": "2026-09-20",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0003",
    "title": "秋山皓太 選手情報",
    "publisher": "B3リーグ",
    "url": "https://www.b3league.jp/player/?key=86&player=22402&team=2727",
    "location": "選手情報 > 英語表記 / 選手情報 > 出身校 / 選手情報 > 立川ダイス / PLAYER STATS > 50試合 / PLAYER STATS / 選手情報 > 所属クラブ",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0012",
    "title": "第70回全日本大学バスケットボール選手権 東海大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/44/type/intercollege/y/2018/s/men",
    "location": "東海大学ROSTER > No.37 秋山皓太 / ROSTER > 4年・大会年2018",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0002",
    "title": "平成26年度男子U-18日本代表チーム候補選手メンバー表",
    "publisher": "日本バスケットボール協会",
    "url": "https://www.japanbasketball.jp/wp/wp-content/uploads/jba2014020-2.pdf",
    "location": "PDF 選手表 > No.28 / PDF 選手表 > No.28 > 生年月日 / PDF 選手表 > No.28 > 所属 / PDF 注記 > 所属・年齢基準日",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0005",
    "title": "大城侑朔 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=10854",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / 基本情報 > 出身校 / クラブ所属履歴 > 2017-18〜2025-26 八王子 / 2024-25 B3RS シーズン成績 / クラブ所属履歴 > 2017-18 八王子 / クラブ所属履歴 > 2025-26 八王子 / シーズン成績 > 2024-25 / クラブ所属履歴 > 八王子",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0013",
    "title": "第67回全日本大学バスケットボール選手権 日本体育大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/5/type/intercollege/y/2015/s/men",
    "location": "日本体育大学ROSTER > No.14 大城侑朔 / ROSTER > 3年・大会年2015",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0004",
    "title": "平成23年度男子U-16日本代表候補選手 参加メンバー表",
    "publisher": "日本バスケットボール協会",
    "url": "https://www.japanbasketball.jp/wp-content/uploads/2ecfbc3e55987cf0d0eee45695bc35cf.pdf",
    "location": "PDF 選手表 > 大城侑朔 > 生年月日 / PDF 選手表 > 大城侑朔 > 所属 / PDF 選手表 > 大城侑朔 / PDF 注記 > 所属・年齢基準日",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0007",
    "title": "土居光 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=36863",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / 基本情報 > 生年月日 / クラブ所属履歴 > 2025-26 東京Z / 2025-26 B3RS シーズン成績 / 2025-26シーズン終了時 / シーズン成績 > 2025-26 / クラブ所属履歴 > 東京Z",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0006",
    "title": "第71回全日本大学バスケットボール選手権 日本体育大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/5/type/intercollege/y/2019/s/men",
    "location": "日本体育大学ROSTER > No.24 > 出身校 / 日本体育大学ROSTER > No.24 / ROSTER > No.24 > SF / 第71回インカレROSTER > 3年 / 出場校 > 日本体育大学",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0014",
    "title": "第73回全日本大学バスケットボール選手権 東海大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/44/type/intercollege/y/2021/s/men",
    "location": "東海大学ROSTER > No.31 松本礼太 / ROSTER > 4年・大会年2021",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0001",
    "title": "福岡第一高等学校 学校案内2022",
    "publisher": "福岡第一高等学校",
    "url": "https://f.f-parama.ed.jp/wp-content/uploads/2022/01/panf2022.pdf",
    "location": "学校案内 > Bリーグ所属卒業生 > 松本礼太 / 学校案内表紙・発行元",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0010",
    "title": "徳島ガンバロウズ 2025-26チーム成績",
    "publisher": "B3リーグ",
    "url": "https://www.b3league.jp/club/tokushima/",
    "location": "徳島ガンバロウズ > No.12 / チーム成績 > No.12 松本礼太 / チーム名",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0008",
    "title": "松本礼太 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=51000138",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / 基本情報 > 生年月日 / 基本情報 > 出身校",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B6W2S0009",
    "title": "松本礼太 B3所属選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=49711",
    "location": "クラブ所属履歴 > 2025-26 徳島 / 2025-26シーズン終了時",
    "accessedAt": "2026-09-22",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0001",
    "title": "富樫勇樹 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=9055",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / 基本情報 > 生年月日 / プロフィール > 出身校（高） / クラブ所属履歴 > 2026-27シーズン 千葉J",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0002",
    "title": "比江島慎 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=8589",
    "location": "選手プロフィール > 選手名 / 選手プロフィール > 英語表記 / 選手プロフィール > 生年月日 / プロフィール > 出身校（高） / プロフィール > 出身校（大） / クラブ所属履歴 > 2026-27シーズン 宇都宮ブレックス",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0004",
    "title": "篠山竜青 川崎ブレイブサンダース公式選手プロフィール",
    "publisher": "川崎ブレイブサンダース",
    "url": "https://kawasaki-bravethunders.com/team/players/detail/id=8224?PlayerID=8484",
    "location": "選手プロフィール > 出身校",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0003",
    "title": "篠山竜青 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=8484",
    "location": "プロフィール > 選手名 / プロフィール > 英語表記 / プロフィール > 生年月日 / クラブ所属履歴 > 2026-27シーズン Kawasaki",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0005",
    "title": "齋藤拓実 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=14301",
    "location": "選手プロフィール > 選手名 / 選手プロフィール > 英語表記 / 選手プロフィール > 生年月日 / クラブ所属履歴 > 2026-27シーズン 名古屋ダイヤモンドドルフィンズ",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0006",
    "title": "齋藤拓実 名古屋ダイヤモンドドルフィンズ公式選手プロフィール",
    "publisher": "名古屋ダイヤモンドドルフィンズ",
    "url": "https://nagoya-dolphins.jp/team/players/detail/id=14611?PlayerID=14301",
    "location": "選手プロフィール > 出身校",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0011",
    "title": "ワタシノB.LEAGUE選手一覧 | 長崎県立長崎西高等学校",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/mybleague_list/?TagID=35:%E9%95%B7%E5%B4%8E%E7%9C%8C%E7%AB%8B%E9%95%B7%E5%B4%8E%E8%A5%BF%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1",
    "location": "検索結果 > 田中大貴",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0009",
    "title": "田中大貴 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=9037",
    "location": "基本情報 > 選手名 / 基本情報 > 生年月日 / プロフィール > 出身校",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0010",
    "title": "田中大貴 東京サンロッカーズ公式選手プロフィール",
    "publisher": "東京サンロッカーズ",
    "url": "https://www.sunrockers.jp/team/players/detail/id=16564?PlayerID=9037",
    "location": "所属クラブの変遷 > 東京サンロッカーズ渋谷（2023-24シーズン以降現在）",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0013",
    "title": "岸本隆一 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=8655",
    "location": "選手プロフィール > 選手名 / 選手プロフィール > 生年月日",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0015",
    "title": "ワタシノB.LEAGUE選手一覧 | 沖縄県立北中城高等学校",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/mybleague_list/?TagID=35:%E6%B2%96%E7%B8%84%E7%9C%8C%E7%AB%8B%E5%8C%97%E4%B8%AD%E5%9F%8E%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1",
    "location": "検索結果：1人 > 岸本隆一",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0014",
    "title": "岸本 隆一選手 契約締結（複数年）のお知らせ",
    "publisher": "京都ハンナリーズ",
    "url": "https://hannaryz.jp/news/detail/id=24529",
    "location": "学歴 > 大東文化大学 / 契約期間 > 2026-27シーズンから2027-28シーズンまで、2年間の複数年契約",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0017",
    "title": "西田優大 シーホース三河公式選手プロフィール",
    "publisher": "シーホース三河",
    "url": "https://go-seahorses.jp/team/players/detail/id=17209?PlayerID=30403",
    "location": "基本情報 > 選手名 / 基本情報 > 生年月日 / 経歴概要 > 高校で大濠高校に進学 / 経歴概要 > 大学では東海大学でプレー / 現在の所属チーム > シーホース三河",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0020",
    "title": "プロバスケットボール選手・金丸晃輔さんにインタビュー【第1回】",
    "publisher": "Meiji NOW（明治大学）",
    "url": "https://meijinow.jp/senior/interview/8831",
    "location": "記事本文 > 2011年政治経済学部卒 / 記事冒頭 > 明大在学時にはバスケットボール部主将を務め",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "B7S0019",
    "title": "14 金丸晃輔選手 佐賀バルーナーズ公式選手プロフィール",
    "publisher": "佐賀バルーナーズ",
    "url": "https://ballooners.jp/team/member/player14",
    "location": "選手情報 > 生年月日 / 経歴 > 2024年～",
    "accessedAt": "2026-09-23",
    "dataStatus": "candidate"
  },
  {
    "id": "SRC000013",
    "title": "ボックススコア：福岡第一 vs 県立四日市工業",
    "publisher": "日本バスケットボール協会（JBA）",
    "url": "https://wintercup2020.japanbasketball.jp/boxscore/?period=18&schedulekey=6898",
    "location": "福岡第一ボックススコア > No.31 / 福岡第一ボックススコア > No.27 / 福岡第一ボックススコア > No.23",
    "accessedAt": "2026-09-19",
    "dataStatus": "candidate"
  },
  {
    "id": "SRC000023",
    "title": "2021年度新入生紹介③ : CHUO BASKETBALL",
    "publisher": "中央大学学友会体育連盟バスケットボール部",
    "url": "http://blog.livedoor.jp/chuo_basket/archives/55638062.html",
    "location": "2021年度新入生紹介③ > #7 松本宗志 / 2021年度新入生紹介③ > ポジションG / ページ名と公開日 > 2021年度新入生紹介",
    "accessedAt": "2026-09-19",
    "dataStatus": "candidate"
  },
  {
    "id": "SRC-CAND-B001-001",
    "title": "福岡第一高校 第96回天皇杯出場チーム",
    "publisher": "日本バスケットボール協会（JBA）",
    "url": "https://zennihon2020-21.japanbasketball.jp/team/1st/men-fukuoka",
    "location": "TEAM DATA > マネージャー / 福岡第一高校 > TEAM DATA",
    "accessedAt": "2026-09-19",
    "dataStatus": "candidate"
  }
] as const;

export const candidatePlayers = [
  {
    "id": "P000016",
    "slug": "p000016",
    "name": "本松 龍斗",
    "cardContext": "期間未確認 · 日本体育大学",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [],
    "careers": [
      {
        "id": "C000033",
        "period": "期間未確認",
        "organization": "日本体育大学",
        "organizationId": "ORG000020",
        "detail": "Student Coach",
        "status": "candidate",
        "sourceIds": [
          "B3S0027",
          "B3S0028"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000079",
    "slug": "p000079",
    "name": "秋山 皓太",
    "cardContext": "期間未確認 · 立川ダイス",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "英字表記",
        "value": "Kota Akiyama",
        "context": "B3公式表記",
        "sourceIds": [
          "B6W2S0003"
        ]
      },
      {
        "label": "生年月日",
        "value": "1996年12月29日",
        "context": "JBA公式生年月日",
        "sourceIds": [
          "B6W2S0002"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000278",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0002"
        ]
      },
      {
        "id": "C000279",
        "period": "期間未確認",
        "organization": "東海大学",
        "organizationId": "ORG000015",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0003",
          "B6W2S0012"
        ]
      },
      {
        "id": "C000280",
        "period": "期間未確認",
        "organization": "立川ダイス",
        "organizationId": "ORG000115",
        "detail": "選手 · 公式戦記録：B3公式戦50試合",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0003"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000080",
    "slug": "p000080",
    "name": "大城 侑朔",
    "cardContext": "期間未確認 · 日本体育大学",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "英字表記",
        "value": "Yusaku Oshiro",
        "context": "B.LEAGUE公式表記",
        "sourceIds": [
          "B6W2S0005"
        ]
      },
      {
        "label": "生年月日",
        "value": "1995年3月1日",
        "context": "JBA公式生年月日",
        "sourceIds": [
          "B6W2S0004"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000281",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0004"
        ]
      },
      {
        "id": "C000282",
        "period": "期間未確認",
        "organization": "日本体育大学",
        "organizationId": "ORG000020",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0005",
          "B6W2S0013"
        ]
      },
      {
        "id": "C000283",
        "period": "2017–2026年",
        "organization": "東京八王子ビートレインズ",
        "organizationId": "ORG000111",
        "detail": "選手 · 公式戦記録：2024-25 B3RS 49試合",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0005"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000081",
    "slug": "p000081",
    "name": "土居 光",
    "cardContext": "期間未確認 · 日本体育大学",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "英字表記",
        "value": "Hikaru Doi",
        "context": "B.LEAGUE公式表記",
        "sourceIds": [
          "B6W2S0007"
        ]
      },
      {
        "label": "生年月日",
        "value": "1998年10月2日",
        "context": "B.LEAGUE公式生年月日",
        "sourceIds": [
          "B6W2S0007"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000284",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "所属を公式資料で確認",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0006"
        ]
      },
      {
        "id": "C000285",
        "period": "期間未確認",
        "organization": "日本体育大学",
        "organizationId": "ORG000020",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0006"
        ]
      },
      {
        "id": "C000286",
        "period": "2025–2026年",
        "organization": "アースフレンズ東京Z",
        "organizationId": "ORG000046",
        "detail": "選手 · 公式戦記録：2025-26 B3RS 23試合",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0007"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000082",
    "slug": "p000082",
    "name": "松本 礼太",
    "cardContext": "期間未確認 · 東海大学",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "英字表記",
        "value": "Reita Matsumoto",
        "context": "B.LEAGUE公式表記",
        "sourceIds": [
          "B6W2S0008"
        ]
      },
      {
        "label": "生年月日",
        "value": "1999年9月18日",
        "context": "B.LEAGUE公式生年月日",
        "sourceIds": [
          "B6W2S0008"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000287",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "所属を公式資料で確認",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0001"
        ]
      },
      {
        "id": "C000288",
        "period": "期間未確認",
        "organization": "東海大学",
        "organizationId": "ORG000015",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0008",
          "B6W2S0014"
        ]
      },
      {
        "id": "C000289",
        "period": "2025–2026年",
        "organization": "徳島ガンバロウズ",
        "organizationId": "ORG000116",
        "detail": "選手 · 公式戦記録：2025-26 B3公式戦30試合",
        "status": "candidate",
        "sourceIds": [
          "B6W2S0009",
          "B6W2S0010"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000083",
    "slug": "p000083",
    "name": "富樫勇樹",
    "cardContext": "期間未確認 · 千葉ジェッツ",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "英字表記",
        "value": "Yuki Togashi",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B7S0001"
        ]
      },
      {
        "label": "生年月日",
        "value": "1993年7月30日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0001"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000300",
        "period": "期間未確認",
        "organization": "千葉ジェッツ",
        "organizationId": "ORG000118",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0001"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000084",
    "slug": "p000084",
    "name": "比江島慎",
    "cardContext": "期間未確認 · 宇都宮ブレックス",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "英字表記",
        "value": "Makoto Hiejima",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B7S0002"
        ]
      },
      {
        "label": "生年月日",
        "value": "1990年8月11日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0002"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000290",
        "period": "期間未確認",
        "organization": "洛南高等学校",
        "organizationId": "ORG000119",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0002"
        ]
      },
      {
        "id": "C000291",
        "period": "期間未確認",
        "organization": "青山学院大学",
        "organizationId": "ORG000030",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0002"
        ]
      },
      {
        "id": "C000292",
        "period": "期間未確認",
        "organization": "宇都宮ブレックス",
        "organizationId": "ORG000047",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0002"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000085",
    "slug": "p000085",
    "name": "篠山竜青",
    "cardContext": "期間未確認 · 川崎ブレイブサンダース",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "英字表記",
        "value": "Ryusei Shinoyama",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B7S0003"
        ]
      },
      {
        "label": "生年月日",
        "value": "1988年7月20日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0003"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000297",
        "period": "期間未確認",
        "organization": "日本大学",
        "organizationId": "ORG000121",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0004"
        ]
      },
      {
        "id": "C000298",
        "period": "期間未確認",
        "organization": "川崎ブレイブサンダース",
        "organizationId": "ORG000122",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0003"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000086",
    "slug": "p000086",
    "name": "齋藤拓実",
    "cardContext": "期間未確認 · 名古屋ダイヤモンドドルフィンズ",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "英字表記",
        "value": "Takumi Saito",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B7S0005"
        ]
      },
      {
        "label": "生年月日",
        "value": "1995年8月11日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0005"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000294",
        "period": "期間未確認",
        "organization": "明治大学",
        "organizationId": "ORG000124",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0006"
        ]
      },
      {
        "id": "C000295",
        "period": "期間未確認",
        "organization": "名古屋ダイヤモンドドルフィンズ",
        "organizationId": "ORG000054",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0005"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000087",
    "slug": "p000087",
    "name": "田中大貴",
    "cardContext": "期間未確認 · 東京サンロッカーズ",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1991年9月3日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0009"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000301",
        "period": "期間未確認",
        "organization": "長崎県立長崎西高等学校",
        "organizationId": "ORG000125",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0011"
        ]
      },
      {
        "id": "C000302",
        "period": "期間未確認",
        "organization": "東海大学",
        "organizationId": "ORG000015",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0009"
        ]
      },
      {
        "id": "C000303",
        "period": "期間未確認",
        "organization": "東京サンロッカーズ",
        "organizationId": "ORG000114",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0010"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000088",
    "slug": "p000088",
    "name": "岸本隆一",
    "cardContext": "期間未確認 · 京都ハンナリーズ",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1990年5月17日",
        "context": "B.LEAGUE公式の生年月日",
        "sourceIds": [
          "B7S0013"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000304",
        "period": "期間未確認",
        "organization": "沖縄県立北中城高等学校",
        "organizationId": "ORG000126",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0015"
        ]
      },
      {
        "id": "C000305",
        "period": "期間未確認",
        "organization": "大東文化大学",
        "organizationId": "ORG000128",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0014"
        ]
      },
      {
        "id": "C000306",
        "period": "期間未確認",
        "organization": "京都ハンナリーズ",
        "organizationId": "ORG000042",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0014"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000089",
    "slug": "p000089",
    "name": "西田優大",
    "cardContext": "期間未確認 · シーホース三河",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1999年3月13日",
        "context": "クラブ公式の生年月日",
        "sourceIds": [
          "B7S0017"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000307",
        "period": "期間未確認",
        "organization": "福岡大学附属大濠高等学校",
        "organizationId": "ORG000127",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0017"
        ]
      },
      {
        "id": "C000308",
        "period": "期間未確認",
        "organization": "東海大学",
        "organizationId": "ORG000015",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0017"
        ]
      },
      {
        "id": "C000309",
        "period": "期間未確認",
        "organization": "シーホース三河",
        "organizationId": "ORG000130",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0017"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000090",
    "slug": "p000090",
    "name": "金丸晃輔",
    "cardContext": "期間未確認 · 佐賀バルーナーズ",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [
      {
        "label": "生年月日",
        "value": "1989年3月8日",
        "context": "クラブ公式の生年月日",
        "sourceIds": [
          "B7S0019"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000311",
        "period": "期間未確認",
        "organization": "明治大学",
        "organizationId": "ORG000124",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0020"
        ]
      },
      {
        "id": "C000312",
        "period": "期間未確認",
        "organization": "佐賀バルーナーズ",
        "organizationId": "ORG000048",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "B7S0019"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000011",
    "slug": "p000011",
    "name": "砂川 琉勇",
    "cardContext": "期間未確認 · 福岡第一高等学校",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [],
    "careers": [
      {
        "id": "C000011",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "SRC000013"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000013",
    "slug": "p000013",
    "name": "松本 宗志",
    "cardContext": "期間未確認 · 福岡第一高等学校",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [],
    "careers": [
      {
        "id": "C000013",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "SRC000013"
        ]
      },
      {
        "id": "C000029",
        "period": "2021年〜",
        "organization": "中央大学",
        "organizationId": "ORG000016",
        "detail": "選手",
        "status": "candidate",
        "sourceIds": [
          "SRC000023"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000017",
    "slug": "p000017",
    "name": "泉美 優知",
    "cardContext": "期間未確認 · 福岡第一高等学校",
    "dataStatus": "candidate",
    "approvalId": null,
    "facts": [],
    "careers": [
      {
        "id": "C000017",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "Manager",
        "status": "candidate",
        "sourceIds": [
          "SRC-CAND-B001-001"
        ]
      }
    ],
    "aliases": []
  }
] as const;
