// Generated by scripts/build_site_master_data.py. Do not edit directly.
export const masterPublication = {
  "approvalId": "APP-AS002-20260921-01",
  "approvedAt": "2026-09-21",
  "verifiedCommit": "4c29a0a"
} as const;

export const masterSources = [
  {
    "id": "B3S0001",
    "title": "ウインターカップ2021 福岡第一対帝京長岡 ボックススコア",
    "publisher": "日本バスケットボール協会",
    "url": "https://wintercup2021.japanbasketball.jp/boxscore/?period=18&schedulekey=7425",
    "location": "福岡第一高等学校 BOX SCORE > No.10 早田 流星 / 試合情報 > 試合期日 / 福岡第一高等学校 BOX SCORE > No.14 鷹野 祐磨 / 福岡第一高等学校 BOX SCORE > No.24 星賀 舞也 / 福岡第一高等学校 BOX SCORE > No.30 岡本 汰稀 / 福岡第一高等学校 BOX SCORE > No.68 岩下 周介 / 福岡第一高等学校 BOX SCORE > No.70 カマレ ムレマ フランシス",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0002",
    "title": "第96回天皇杯 福岡第一高校ロスター",
    "publisher": "日本バスケットボール協会",
    "url": "https://zennihon2020-21.japanbasketball.jp/team/1st/men-fukuoka",
    "location": "福岡第一高校 > プレイヤー > No.10 早田 流星 / 福岡第一高校 > プレイヤー > No.24 星賀 舞也 / 福岡第一高校 > プレイヤー > No.1 當山 修梧 / 福岡第一高校 > プレイヤー > No.65 キエキエトピー アリ",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0003",
    "title": "2019年度男子U16日本代表 第1次強化合宿メンバー",
    "publisher": "日本バスケットボール協会",
    "url": "https://iwate.japanbasketball.jp/manage/wp-content/uploads/2019/04/42d4fca113768eb1273ef8bdba5e06eb.pdf",
    "location": "PDF 1ページ > TAKANO, Yuma / PDF 1ページ > 生年月日",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0006",
    "title": "第101回天皇杯 日本体育大学ロスター",
    "publisher": "日本バスケットボール協会",
    "url": "https://zennihon2025-26.japanbasketball.jp/team/fin/m02/",
    "location": "日本体育大学 > No.10 / 日本体育大学 > No.10 > 生年月日",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0007",
    "title": "第77回インカレ 日本体育大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/5/type/intercollege/y/2025/s/men",
    "location": "日本体育大学 ROSTER > No.10 / 日本体育大学 > 大会成績 > 早田流星",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0008",
    "title": "第76回インカレ 青山学院大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/9/type/intercollege/y/2024/s/men",
    "location": "青山学院大学 ROSTER > No.25",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0009",
    "title": "第76回インカレ 青山学院大学対天理大学",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/detail/id/1194/type/intercollege/s/men",
    "location": "青山学院大学 BOX SCORE > No.25",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0010",
    "title": "第77回インカレ 九州国際大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/230/type/intercollege/y/2025/s/men",
    "location": "九州国際大学 ROSTER > No.23 / 九州国際大学 > 大会成績 > 岡本汰稀",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0011",
    "title": "第74回インカレ 東海大学九州ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/12/type/intercollege/y/2022/s/men",
    "location": "東海大学九州 ROSTER > No.17",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0012",
    "title": "第75回インカレ 東海大学九州ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/12/type/intercollege/y/2023/s/men",
    "location": "東海大学九州 ROSTER > No.17",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0013",
    "title": "第76回インカレ 東海大学九州ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/12/type/intercollege/y/2024/s/men",
    "location": "東海大学九州 ROSTER > No.17",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0014",
    "title": "第77回インカレ 東海大学九州ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/12/type/intercollege/y/2025/s/men",
    "location": "東海大学九州 ROSTER > No.17 / 東海大学九州 > 大会成績 > 岩下周介",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0015",
    "title": "第76回インカレ 山梨学院大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/204/type/intercollege/y/2024/s/men",
    "location": "山梨学院大学 ROSTER > No.70",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0016",
    "title": "第77回インカレ 山梨学院大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/204/type/intercollege/y/2025/s/men",
    "location": "山梨学院大学 ROSTER > No.70",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0017",
    "title": "第77回インカレ 山梨学院大学対名古屋学院大学",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/detail/id/1365/type/intercollege/s/men",
    "location": "山梨学院大学 BOX SCORE > No.70",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0018",
    "title": "第73回インカレ 専修大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/25/type/intercollege/y/2021/s/men",
    "location": "専修大学 ROSTER > No.3",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0019",
    "title": "第74回インカレ 専修大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/25/type/intercollege/y/2022/s/men",
    "location": "専修大学 ROSTER > No.3",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0020",
    "title": "第75回インカレ 専修大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/25/type/intercollege/y/2023/s/men",
    "location": "専修大学 ROSTER > No.3",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0021",
    "title": "第76回インカレ 専修大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/25/type/intercollege/y/2024/s/men",
    "location": "専修大学 ROSTER > No.3 / 専修大学 > 大会成績 > 當山修梧",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0022",
    "title": "キエキエ・トピー・アリ 選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=36413",
    "location": "選手プロフィール > 選手名 / 選手プロフィール > 英語表記 / 選手プロフィール > 生年月日",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0023",
    "title": "第74回インカレ 日本経済大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/180/type/intercollege/y/2022/s/men",
    "location": "日本経済大学 ROSTER > No.3",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0024",
    "title": "第75回インカレ 日本経済大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/180/type/intercollege/y/2023/s/men",
    "location": "日本経済大学 ROSTER > No.33",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0025",
    "title": "第76回インカレ 日本経済大学ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/180/type/intercollege/y/2024/s/men",
    "location": "日本経済大学 ROSTER > No.33",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B3S0026",
    "title": "第76回インカレ 日本経済大学対中央大学",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/detail/id/1214/type/intercollege/s/men",
    "location": "日本経済大学 BOX SCORE > No.33",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W1S0001",
    "title": "平成29年度 バスケットボール男子U16日本代表チーム メンバー表",
    "publisher": "日本バスケットボール協会",
    "url": "https://www.japanbasketball.jp/wp-content/uploads/U16men-member_20180330.pdf",
    "location": "PDF 1ページ > 河村勇輝欄 / PDF 1ページ > KAWAMURA Yuki / PDF 1ページ > 生年月日 / PDF 1ページ > 所属欄 / PDF 1ページ > 選手一覧 / PDF 1ページ > 学年欄 / PDF 1ページ > 発表日と選手欄",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W1S0002",
    "title": "2020年度男子日本代表Bチーム メンバー",
    "publisher": "日本バスケットボール協会",
    "url": "https://www.japanbasketball.jp/wp-content/uploads/National-B-Team_Men_member_20200806.pdf",
    "location": "PDF 選手一覧 > 河村勇輝欄 / PDF 選手一覧 / PDF 選手一覧 > 学年欄 / PDF 発表日と選手欄 / PDF 選手一覧 > 所属欄",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W1S0003",
    "title": "河村勇輝 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=30460",
    "location": "クラブ所属履歴 > 2019-20 三遠 / 選手プロフィール > クラブ所属履歴 / クラブ所属履歴 / クラブ所属履歴 > 横浜BC / 2023-24 B1 シーズン成績",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W1S0004",
    "title": "Grizzlies promote Yuki Kawamura to two-way contract",
    "publisher": "Memphis Grizzlies",
    "url": "https://www.nba.com/grizzlies/news/grizzlies-promote-yuki-kawamura-to-two-way-contract",
    "location": "公式発表本文 / 公式発表本文 > guard Yuki Kawamura / 公式発表の公開日時 / 公式発表の発行元と本文",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W1S0007",
    "title": "日本経済大学 2024新人戦ロスター",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/180/type/rookie/y/2024/s/men",
    "location": "日本経済大学 ROSTER > No.3 / 日本経済大学 ROSTER",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W1S0008",
    "title": "WUBS 2025 日本学生選抜メンバー",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/index/show-pdf/url/aHR0cHM6Ly9kMmEwdjF4N3F2eGw2Yy5jbG91ZGZyb250Lm5ldC9maWxlcy9zcG9ocF9qdWJmL25ld3MvNjg5MmMzMGU0Y2U3ZS5wZGY%3D",
    "location": "PDF 日本学生選抜 > 児玉ジュニア欄 / PDF 日本学生選抜 > KODAMA Junior / PDF 日本学生選抜 > 生年月日",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W1S0009",
    "title": "児玉 ジュニア選手 契約締結（新規）のお知らせ",
    "publisher": "三遠ネオフェニックス",
    "url": "https://www.neophoenix.jp/news/detail/id=21966",
    "location": "選手プロフィール > 出身校・受賞歴 / 選手プロフィール > WC2023優勝 / 選手プロフィール > 受賞歴 / ニュース本文 / ニュース公開日 / ニュース本文と経歴欄 / 契約締結発表 / 選手プロフィール欄",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W1S0010",
    "title": "児玉ジュニア B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=51000552",
    "location": "2025-26 B1 シーズン成績",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W1S0011",
    "title": "児玉 ジュニア選手 契約締結（継続）のお知らせ",
    "publisher": "三遠ネオフェニックス",
    "url": "https://www.neophoenix.jp/news/detail/id=24999",
    "location": "ニュース本文 / ニュース公開日",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W2S0002",
    "title": "河合瑠那選手 特別指定選手登録のお知らせ",
    "publisher": "横浜エクセレンス",
    "url": "https://yokohama-ex.jp/team/pages/id=22814",
    "location": "発行元・本文",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W2S0006",
    "title": "長岡大杜 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=52467",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / 基本情報 > 生年月日 / 基本情報 > 身長 / 基本情報 > 体重 / 基本情報 > 出身地 / 基本情報 > 出身校 / 2025-26 B3 シーズン成績",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W2S0007",
    "title": "2025-26シーズン 新規リーグエントリー選手のお知らせ",
    "publisher": "B3リーグ",
    "url": "https://www.b3league.jp/archives/45352",
    "location": "新規リーグエントリー選手欄 / 選手プロフィール > 出身校 / 公開日 / 選手プロフィール > 背番号 / 選手プロフィール > ポジション / 選手所属欄",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W3S0001",
    "title": "専大スポーツ第559号 2017年度期待のニューパワー",
    "publisher": "専修大学",
    "url": "https://www.senshu-u.ac.jp/albums/abm.php?d=2115&f=abm00003946.pdf&n=2017%E5%B9%B44%E6%9C%88%E5%8F%B7%EF%BC%88%E7%AC%AC559%E5%8F%B7%EF%BC%8911%E9%9D%A2.pdf",
    "location": "PDF 11面 > バスケットボール部 > 重冨周希 / PDF 11面 > バスケットボール部 / PDF見出し > 2017年度 / PDF 11面 > バスケットボール部 > 重冨友希 / 資料内の組織名・経歴欄",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W3S0002",
    "title": "重冨周希 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=5100000076",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / 基本情報 > 生年月日 / 基本情報 > 身長 / 基本情報 > 体重 / クラブ所属履歴 / 選手プロフィール / シーズン成績 / クラブ所属履歴 > 2026-27湘南 / 2026-27選手プロフィール / 資料内の組織名・経歴欄",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W3S0003",
    "title": "重冨友希 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=40173",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / 基本情報 > 生年月日 / 基本情報 > 身長 / 基本情報 > 体重",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W3S0004",
    "title": "重冨友希選手 2025-26シーズン契約合意（継続）",
    "publisher": "山口パッツファイブ",
    "url": "https://patsfive.com/shigetomi2526/",
    "location": "プレイ歴 / 契約選手プロフィール / 契約合意発表 / 発表見出し・本文 / 資料内の組織名・経歴欄",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W3S0005",
    "title": "キエキエ・トピー・アリ B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=36413",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / 基本情報 > 生年月日 / 2020-21鹿児島シーズン成績 / シーズン成績",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W3S0006",
    "title": "キエキエ・トピー・アリ選手 2024-25シーズン契約合意",
    "publisher": "横浜エクセレンス",
    "url": "https://yokohama-ex.jp/team/pages/id=21831",
    "location": "経歴 > 2021.01-03鹿児島 / 契約合意本文 / 契約選手プロフィール / 発表見出し / 資料内の組織名・経歴欄",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W3S0007",
    "title": "キエキエ・トピー・アリ選手 契約満了",
    "publisher": "横浜エクセレンス",
    "url": "https://yokohama-ex.jp/team/pages/id=22085",
    "location": "契約満了本文",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W3S0008",
    "title": "遥天翼 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=8642",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / 基本情報 > 生年月日",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W3S0009",
    "title": "遥天翼氏 2025-26シーズン契約（新規）",
    "publisher": "熊本ヴォルターズ",
    "url": "https://www.volters.jp/news/detail/id=16536",
    "location": "プロフィール > 出身地 / 経歴 > 福岡第一高校 / 経歴 > 東海大学 / 経歴 > 2011-13 三菱電機ダイヤモンドドルフィンズ / 選手経歴 > 2011-13 三菱電機ダイヤモンドドルフィンズ / 経歴 > 2013-14 三菱電機ダイヤモンドドルフィンズ名古屋 / 選手経歴 > 2013-14 三菱電機ダイヤモンドドルフィンズ名古屋 / 経歴 > 2014-16 熊本ヴォルターズ / 選手経歴 > 2014-16 熊本ヴォルターズ / 経歴 > 2016-18 新潟アルビレックスBB / 選手経歴 > 2016-18 新潟アルビレックスBB / 経歴 > 2018-19 ライジングゼファー福岡 / 選手経歴 > 2018-19 ライジングゼファー福岡 / 経歴 > 2019-20 東京サンレーヴス / 選手経歴 > 2019-20 東京サンレーヴス / 経歴 > 2020-22 茨城ロボッツ / 選手経歴 > 2020-22 茨城ロボッツ / 経歴 > 2022-25 茨城U15 / 経歴 > U15ヘッドコーチ / 経歴 > 2025- 熊本 / 発表見出し・経歴 / 資料内の組織名・経歴欄",
    "accessedAt": "2026-09-20",
    "dataStatus": "master"
  },
  {
    "id": "B4W4S0001",
    "title": "B.LEAGUE DRAFT 2026 候補選手一覧",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/draft2026/prospects/list/",
    "location": "候補選手一覧 > 今泉 太陽 > プロフィール / 候補選手一覧 > 今泉 太陽 > 生年月日 / 候補選手一覧 > 今泉 太陽 > ポジション / 候補選手一覧 > 今泉 太陽 > 身長 / 候補選手一覧 > 今泉 太陽 > 体重 / 候補選手一覧 > 今泉 太陽 / 今泉 太陽 > 経歴 > 2019年4月-2022年3月 / 今泉 太陽 > 経歴 / 今泉 太陽 > 経歴 > 2022年4月-現在 / 候補選手一覧 > 崎濱 秀真 > プロフィール / 候補選手一覧 > 崎濱 秀真 > 生年月日 / 候補選手一覧 > 崎濱 秀真 > ポジション / 候補選手一覧 > 崎濱 秀真 > 身長 / 候補選手一覧 > 崎濱 秀真 > 体重 / 候補選手一覧 > 崎濱 秀真 / 崎濱 秀真 > 経歴 > 2019年4月-2022年3月 / 崎濱 秀真 > 経歴 / 崎濱 秀真 > 経歴 > 2022年4月-現在 / 両選手の経歴欄",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B4W4S0002",
    "title": "第77回全日本大学バスケットボール選手権大会 日本経済大学",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/180/type/intercollege/y/2025/s/men",
    "location": "ROSTER > No.8 今泉 太陽 / ROSTER・STATS > No.8 / STATS > No.8 今泉 太陽 / 大学名・ROSTER",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B4W4S0003",
    "title": "第74回全日本大学バスケットボール選手権大会 新潟経営大学",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/4/type/intercollege/y/2022/s/men",
    "location": "ROSTER > No.23 崎濱 秀真",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B4W4S0004",
    "title": "第76回全日本大学バスケットボール選手権大会 新潟経営大学",
    "publisher": "全日本大学バスケットボール連盟",
    "url": "https://jubf.jp/game/university-detail/id/4/type/intercollege/y/2024/s/men",
    "location": "ROSTER・STATS > No.23 / STATS > No.23 崎濱 秀真 / 大学名・ROSTER",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0001",
    "title": "#17 崎濱秀斗選手加入（特別指定選手）のお知らせ",
    "publisher": "琉球ゴールデンキングス",
    "url": "https://goldenkings.jp/retired_numbers_26/detail_26/id=21221",
    "location": "選手プロフィール > 生年月日 / 選手プロフィール > 身長 / 選手プロフィール > 体重 / 選手プロフィール > ポジション / 選手プロフィール > 経歴 > 2021-24 / 選手プロフィール > 経歴 / 本文 > 福岡第一高校時代 / 選手プロフィール > 経歴 > 2024 / 本文 > キングスU18での活動経験 / 本文 > 学業とバスケットボール / 選手プロフィール > 経歴 > 2024- / 加入発表本文 / 発行元・加入発表本文 / 本文・選手プロフィール > 経歴",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0002",
    "title": "崎濱秀斗 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=51000486",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / 基本情報 > 出身校 / シーズン成績",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0003",
    "title": "#17 崎濱秀斗選手 特別指定選手の活動終了のご報告",
    "publisher": "琉球ゴールデンキングス",
    "url": "https://goldenkings.jp/clubkings/pages/id=25788",
    "location": "主な経歴 > 2024-26 / 発表本文",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0004",
    "title": "轟 琉維選手 2024-25シーズン 特別指定選手 加入のお知らせ",
    "publisher": "アルバルク東京",
    "url": "https://www.alvark-tokyo.jp/news/detail/team/id=19876",
    "location": "選手プロフィール > 生年月日 / 選手プロフィール > ポジション / 選手プロフィール > 出身校 / 本文 > 東海大学2年 / 加入発表本文 / 発表見出し・本文 / 発行元・加入発表本文 / 公開日・加入発表本文",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0005",
    "title": "#8 轟 琉維選手 リーグ登録完了のお知らせ",
    "publisher": "アルバルク東京",
    "url": "https://www.alvark-tokyo.jp/news/detail/event/team/media/id=19920",
    "location": "選手プロフィール > 出身校 / 発表本文",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0006",
    "title": "2/8（土）仙台89ERS戦 ゲームレポート",
    "publisher": "アルバルク東京",
    "url": "https://www.alvark-tokyo.jp/news/detail/game/id=250208",
    "location": "ゲームレポート冒頭",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0007",
    "title": "轟 琉維選手 2024-25シーズン 特別指定選手 活動終了のご報告",
    "publisher": "アルバルク東京",
    "url": "https://www.alvark-tokyo.jp/news/detail/team/id=20126",
    "location": "発表本文 / 活動終了本文 > 2025年3月5日",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0008",
    "title": "轟琉維 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=51000457",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / 基本情報 > 身長 / 基本情報 > 体重 / クラブ所属履歴 > 2025-26 / シーズン成績 > 2025-26 B1 / シーズン成績・試合成績 / クラブ所属履歴 > 佐賀 / クラブ所属履歴 > 2025-26 佐賀",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0009",
    "title": "佐藤涼成選手 2024-25シーズン 特別指定選手登録のお知らせ",
    "publisher": "横浜ビー・コルセアーズ",
    "url": "https://b-corsairs.com/news/team_20241221_1/",
    "location": "登録発表本文 / 発表見出し・本文 / 登録発表 > 活動期間 / 発行元・登録発表本文 / 活動期間 > 2025年1月1日 / 活動期間 > 2025年3月5日",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0010",
    "title": "佐藤涼成 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=51000447",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / シーズン成績",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0011",
    "title": "#88 佐藤 涼成選手 契約合意（新規）のお知らせ",
    "publisher": "広島ドラゴンフライズ",
    "url": "https://hiroshimadragonflies.com/news/detail/id=21158",
    "location": "選手プロフィール > 生年月日 / 契約発表本文 / 経歴 > 2025年- / 選手プロフィール > 出身校 / 発行元・契約発表本文",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0012",
    "title": "2026-27シーズン 契約合意（継続）選手のお知らせ",
    "publisher": "広島ドラゴンフライズ",
    "url": "https://hiroshimadragonflies.com/news/detail/id=24483",
    "location": "佐藤涼成 > GMコメント",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0013",
    "title": "河合瑠那選手 特別指定選手登録のお知らせ",
    "publisher": "横浜エクセレンス",
    "url": "https://yokohama-ex.jp/team/pages/id=22814",
    "location": "登録発表本文 / 発表見出し・本文 / 特別指定選手登録発表",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0014",
    "title": "河合瑠那 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=51000607",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / シーズン成績 > 2025-26 B2 / シーズン成績",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0015",
    "title": "河合瑠那 選手 特別指定選手活動終了のお知らせ",
    "publisher": "横浜エクセレンス",
    "url": "https://yokohama-ex.jp/news/detail/id=25440",
    "location": "公開日・発表本文 / 発表本文 / 発行元・活動終了本文 / 2025-26シーズンをもって活動終了",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  }
] as const;

export const masterPlayers = [
  {
    "id": "P000010",
    "slug": "p000010",
    "name": "當山 修梧",
    "cardContext": "期間未確認 · 専修大学",
    "dataStatus": "master",
    "approvalId": "APP-AS001-20260921-01",
    "facts": [],
    "careers": [
      {
        "id": "C000010",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B3S0002"
        ]
      },
      {
        "id": "C000031",
        "period": "期間未確認",
        "organization": "専修大学",
        "organizationId": "ORG000018",
        "detail": "選手 · 公式戦記録：3試合・29:11",
        "status": "master",
        "sourceIds": [
          "B3S0018",
          "B3S0019",
          "B3S0020",
          "B3S0021"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000014",
    "slug": "p000014",
    "name": "キエキエ トピー アリ",
    "cardContext": "期間未確認 · 横浜エクセレンス",
    "dataStatus": "master",
    "approvalId": "APP-AS002-20260921-01",
    "facts": [
      {
        "label": "英字表記",
        "value": "Topy Ali Kiekie",
        "context": "B.LEAGUE公式プロフィールの英語表記",
        "sourceIds": [
          "B3S0022",
          "B4W3S0005"
        ]
      },
      {
        "label": "生年月日",
        "value": "2003年3月23日",
        "context": "生年月日を掲載",
        "sourceIds": [
          "B3S0022",
          "B4W3S0005"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000014",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B3S0002"
        ]
      },
      {
        "id": "C000030",
        "period": "期間未確認",
        "organization": "日本経済大学",
        "organizationId": "ORG000017",
        "detail": "選手 · 学年：2年 / 3年 / 4年 · 公式戦記録：34:00・21得点",
        "status": "master",
        "sourceIds": [
          "B3S0023",
          "B3S0024",
          "B3S0025",
          "B3S0026"
        ]
      },
      {
        "id": "C000240",
        "period": "期間未確認",
        "organization": "鹿児島レブナイズ",
        "organizationId": "ORG000101",
        "detail": "選手 · 公式戦記録：2020-21 B3 18試合369分24秒",
        "status": "master",
        "sourceIds": [
          "B4W3S0006",
          "B4W3S0005"
        ]
      },
      {
        "id": "C000241",
        "period": "期間未確認",
        "organization": "横浜エクセレンス",
        "organizationId": "ORG000090",
        "detail": "選手 · 公式戦記録：2024-25 B3RS 4試合・B3PO 3試合",
        "status": "master",
        "sourceIds": [
          "B4W3S0006",
          "B4W3S0005",
          "B4W3S0007"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000028",
    "slug": "p000028",
    "name": "佐藤 涼成",
    "cardContext": "2025年〜 · 広島ドラゴンフライズ",
    "dataStatus": "master",
    "approvalId": "APP-B005-20260921-01",
    "facts": [
      {
        "label": "英字表記",
        "value": "Ryosei Sato",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B5W1S0010"
        ]
      },
      {
        "label": "生年月日",
        "value": "2003年7月9日",
        "context": "クラブ公式プロフィール",
        "sourceIds": [
          "B5W1S0011"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000265",
        "period": "2025年",
        "organization": "横浜ビー・コルセアーズ",
        "organizationId": "ORG000055",
        "detail": "選手 · 登録区分：特別指定選手 · 公式戦記録：2024-25 B1 7試合 · 活動期間：2025-01-01〜2025-03-05",
        "status": "master",
        "sourceIds": [
          "B5W1S0009",
          "B5W1S0010"
        ]
      },
      {
        "id": "C000266",
        "period": "2025年〜",
        "organization": "広島ドラゴンフライズ",
        "organizationId": "ORG000110",
        "detail": "選手 · 契約区分：特別指定選手（プロ契約） · 公式戦記録：2025-26 B1 25試合 · 契約継続：2026-27以降の複数年契約",
        "status": "master",
        "sourceIds": [
          "B5W1S0011",
          "B5W1S0010",
          "B5W1S0012"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000029",
    "slug": "p000029",
    "name": "早田 流星",
    "cardContext": "期間未確認 · 日本体育大学",
    "dataStatus": "master",
    "approvalId": "APP-AS001-20260921-01",
    "facts": [
      {
        "label": "生年月日",
        "value": "2003年7月18日",
        "context": "生年月日を掲載",
        "sourceIds": [
          "B3S0006"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000047",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手 · 公式戦記録：12:53",
        "status": "master",
        "sourceIds": [
          "B3S0001",
          "B3S0002"
        ]
      },
      {
        "id": "C000214",
        "period": "期間未確認",
        "organization": "日本体育大学",
        "organizationId": "ORG000020",
        "detail": "選手 · 学年：4年 · 公式戦記録：2試合",
        "status": "master",
        "sourceIds": [
          "B3S0007"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000030",
    "slug": "p000030",
    "name": "鷹野 祐磨",
    "cardContext": "期間未確認 · 福岡第一高等学校",
    "dataStatus": "master",
    "approvalId": "APP-AS001-20260921-01",
    "facts": [
      {
        "label": "英字表記",
        "value": "Yuma Takano",
        "context": "公式資料の英語表記",
        "sourceIds": [
          "B3S0003"
        ]
      },
      {
        "label": "生年月日",
        "value": "2003年11月28日",
        "context": "生年月日を掲載",
        "sourceIds": [
          "B3S0003"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000048",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手 · 学年：1年",
        "status": "master",
        "sourceIds": [
          "B3S0001",
          "B3S0003"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000031",
    "slug": "p000031",
    "name": "星賀 舞也",
    "cardContext": "期間未確認 · 青山学院大学",
    "dataStatus": "master",
    "approvalId": "APP-AS001-20260921-01",
    "facts": [],
    "careers": [
      {
        "id": "C000049",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手 · 公式戦記録：27:07",
        "status": "master",
        "sourceIds": [
          "B3S0001",
          "B3S0002"
        ]
      },
      {
        "id": "C000215",
        "period": "期間未確認",
        "organization": "青山学院大学",
        "organizationId": "ORG000030",
        "detail": "選手 · 学年：3年 · 公式戦記録：28:59",
        "status": "master",
        "sourceIds": [
          "B3S0008",
          "B3S0009"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000032",
    "slug": "p000032",
    "name": "岡本 汰稀",
    "cardContext": "期間未確認 · 九州国際大学",
    "dataStatus": "master",
    "approvalId": "APP-AS001-20260921-01",
    "facts": [],
    "careers": [
      {
        "id": "C000050",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B3S0001"
        ]
      },
      {
        "id": "C000216",
        "period": "期間未確認",
        "organization": "九州国際大学",
        "organizationId": "ORG000094",
        "detail": "選手 · 学年：4年 · 公式戦記録：2試合",
        "status": "master",
        "sourceIds": [
          "B3S0010"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000033",
    "slug": "p000033",
    "name": "岩下 周介",
    "cardContext": "期間未確認 · 東海大学九州",
    "dataStatus": "master",
    "approvalId": "APP-AS001-20260921-01",
    "facts": [],
    "careers": [
      {
        "id": "C000051",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B3S0001"
        ]
      },
      {
        "id": "C000217",
        "period": "期間未確認",
        "organization": "東海大学九州",
        "organizationId": "ORG000095",
        "detail": "選手 · 学年：1年 / 2年 / 3年 / 4年 · 公式戦記録：2試合・58:49",
        "status": "master",
        "sourceIds": [
          "B3S0011",
          "B3S0012",
          "B3S0013",
          "B3S0014"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000034",
    "slug": "p000034",
    "name": "カマレ ムレマ フランシス",
    "cardContext": "期間未確認 · 山梨学院大学",
    "dataStatus": "master",
    "approvalId": "APP-AS001-20260921-01",
    "facts": [],
    "careers": [
      {
        "id": "C000052",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手 · 公式戦記録：07:19",
        "status": "master",
        "sourceIds": [
          "B3S0001"
        ]
      },
      {
        "id": "C000218",
        "period": "期間未確認",
        "organization": "山梨学院大学",
        "organizationId": "ORG000096",
        "detail": "選手 · 学年：3年 / 4年 · 公式戦記録：15:26",
        "status": "master",
        "sourceIds": [
          "B3S0015",
          "B3S0016",
          "B3S0017"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000064",
    "slug": "p000064",
    "name": "河村 勇輝",
    "cardContext": "期間未確認 · メンフィス・グリズリーズ",
    "dataStatus": "master",
    "approvalId": "APP-AS001-20260921-01",
    "facts": [
      {
        "label": "英字表記",
        "value": "Yuki Kawamura",
        "context": "JBA公式メンバー表の英語表記",
        "sourceIds": [
          "B4W1S0001"
        ]
      },
      {
        "label": "生年月日",
        "value": "2001年5月2日",
        "context": "生年月日を掲載",
        "sourceIds": [
          "B4W1S0001"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000219",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手 · 学年：1年",
        "status": "master",
        "sourceIds": [
          "B4W1S0001"
        ]
      },
      {
        "id": "C000220",
        "period": "期間未確認",
        "organization": "東海大学",
        "organizationId": "ORG000015",
        "detail": "選手 · 学年：1年",
        "status": "master",
        "sourceIds": [
          "B4W1S0002"
        ]
      },
      {
        "id": "C000221",
        "period": "期間未確認",
        "organization": "三遠ネオフェニックス",
        "organizationId": "ORG000097",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B4W1S0003"
        ]
      },
      {
        "id": "C000222",
        "period": "期間未確認",
        "organization": "横浜ビー・コルセアーズ",
        "organizationId": "ORG000055",
        "detail": "選手 · 公式戦記録：2023-24 B1 56試合",
        "status": "master",
        "sourceIds": [
          "B4W1S0003"
        ]
      },
      {
        "id": "C000223",
        "period": "期間未確認",
        "organization": "メンフィス・グリズリーズ",
        "organizationId": "ORG000098",
        "detail": "選手 · 契約区分：Two-Way contract",
        "status": "master",
        "sourceIds": [
          "B4W1S0004"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000065",
    "slug": "p000065",
    "name": "児玉 ジュニア",
    "cardContext": "期間未確認 · 三遠ネオフェニックス",
    "dataStatus": "master",
    "approvalId": "APP-AS002-20260921-01",
    "facts": [
      {
        "label": "英字表記",
        "value": "Junior Kodama",
        "context": "JUBF公式資料の英語表記",
        "sourceIds": [
          "B4W1S0008"
        ]
      },
      {
        "label": "生年月日",
        "value": "2006年3月15日",
        "context": "生年月日を掲載",
        "sourceIds": [
          "B4W1S0008"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000224",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B4W1S0009"
        ]
      },
      {
        "id": "C000225",
        "period": "期間未確認",
        "organization": "日本経済大学",
        "organizationId": "ORG000017",
        "detail": "選手 · 学年：1年 / 2年",
        "status": "master",
        "sourceIds": [
          "B4W1S0007",
          "B4W1S0008",
          "B4W1S0009"
        ]
      },
      {
        "id": "C000226",
        "period": "期間未確認",
        "organization": "三遠ネオフェニックス",
        "organizationId": "ORG000097",
        "detail": "選手 · 公式戦記録：2025-26 B1 44試合",
        "status": "master",
        "sourceIds": [
          "B4W1S0009",
          "B4W1S0010",
          "B4W1S0011"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000066",
    "slug": "p000066",
    "name": "河合 瑠那",
    "cardContext": "2026年 · 横浜エクセレンス",
    "dataStatus": "master",
    "approvalId": "APP-B005-20260921-01",
    "facts": [
      {
        "label": "英字表記",
        "value": "Runa Kawai",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B5W1S0014"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000229",
        "period": "2026年",
        "organization": "横浜エクセレンス",
        "organizationId": "ORG000090",
        "detail": "選手 · 登録区分：特別指定選手 · 公式戦記録：2025-26 B2 1試合3分33秒・2得点 · 活動終了発表：2026-05-21 · 自由交渉選手リスト発表：2026-05-21",
        "status": "master",
        "sourceIds": [
          "B5W1S0013",
          "B5W1S0014",
          "B5W1S0015"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000067",
    "slug": "p000067",
    "name": "長岡 大杜",
    "cardContext": "期間未確認 · 山口パッツファイブ",
    "dataStatus": "master",
    "approvalId": "APP-AS002-20260921-01",
    "facts": [
      {
        "label": "英字表記",
        "value": "Daito Nagaoka",
        "context": "B.LEAGUE公式プロフィールの英語表記",
        "sourceIds": [
          "B4W2S0006"
        ]
      },
      {
        "label": "生年月日",
        "value": "2007年10月17日",
        "context": "B.LEAGUE公式プロフィールの生年月日",
        "sourceIds": [
          "B4W2S0006"
        ]
      },
      {
        "label": "身長",
        "value": "178cm",
        "context": "B.LEAGUE公式プロフィールの身長",
        "sourceIds": [
          "B4W2S0006"
        ]
      },
      {
        "label": "体重",
        "value": "77kg",
        "context": "B.LEAGUE公式プロフィールの体重",
        "sourceIds": [
          "B4W2S0006"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000230",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B4W2S0006",
          "B4W2S0007"
        ]
      },
      {
        "id": "C000231",
        "period": "期間未確認",
        "organization": "山口パッツファイブ",
        "organizationId": "ORG000100",
        "detail": "選手 · 公式戦記録：2025-26 B3 1試合1分12秒",
        "status": "master",
        "sourceIds": [
          "B4W2S0007",
          "B4W2S0006"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000068",
    "slug": "p000068",
    "name": "重冨 周希",
    "cardContext": "期間未確認 · ウォルガ湘南",
    "dataStatus": "master",
    "approvalId": "APP-AS002-20260921-01",
    "facts": [
      {
        "label": "英字表記",
        "value": "Shuki Shigetomi",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B4W3S0002"
        ]
      },
      {
        "label": "生年月日",
        "value": "1998年6月9日",
        "context": "生年月日を掲載",
        "sourceIds": [
          "B4W3S0002"
        ]
      },
      {
        "label": "身長",
        "value": "174cm",
        "context": "登録身長",
        "sourceIds": [
          "B4W3S0002"
        ]
      },
      {
        "label": "体重",
        "value": "74kg",
        "context": "登録体重",
        "sourceIds": [
          "B4W3S0002"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000232",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "所属を公式資料で確認",
        "status": "master",
        "sourceIds": [
          "B4W3S0001"
        ]
      },
      {
        "id": "C000233",
        "period": "期間未確認",
        "organization": "専修大学",
        "organizationId": "ORG000018",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B4W3S0001"
        ]
      },
      {
        "id": "C000234",
        "period": "期間未確認",
        "organization": "ライジングゼファー福岡",
        "organizationId": "ORG000040",
        "detail": "選手 · 公式戦記録：2023-24 B2 53試合",
        "status": "master",
        "sourceIds": [
          "B4W3S0002"
        ]
      },
      {
        "id": "C000235",
        "period": "期間未確認",
        "organization": "ウォルガ湘南",
        "organizationId": "ORG000050",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B4W3S0002"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000069",
    "slug": "p000069",
    "name": "重冨 友希",
    "cardContext": "期間未確認 · 山口パッツファイブ",
    "dataStatus": "master",
    "approvalId": "APP-AS002-20260921-01",
    "facts": [
      {
        "label": "英字表記",
        "value": "Yuuki Shigetomi",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B4W3S0003"
        ]
      },
      {
        "label": "生年月日",
        "value": "1998年6月9日",
        "context": "生年月日を掲載",
        "sourceIds": [
          "B4W3S0003"
        ]
      },
      {
        "label": "身長",
        "value": "174cm",
        "context": "登録身長",
        "sourceIds": [
          "B4W3S0003"
        ]
      },
      {
        "label": "体重",
        "value": "75kg",
        "context": "登録体重",
        "sourceIds": [
          "B4W3S0003"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000236",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "所属を公式資料で確認",
        "status": "master",
        "sourceIds": [
          "B4W3S0001"
        ]
      },
      {
        "id": "C000237",
        "period": "期間未確認",
        "organization": "専修大学",
        "organizationId": "ORG000018",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B4W3S0001"
        ]
      },
      {
        "id": "C000238",
        "period": "期間未確認",
        "organization": "ライジングゼファー福岡",
        "organizationId": "ORG000040",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B4W3S0004"
        ]
      },
      {
        "id": "C000239",
        "period": "期間未確認",
        "organization": "山口パッツファイブ",
        "organizationId": "ORG000100",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B4W3S0004"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000070",
    "slug": "p000070",
    "name": "遥 天翼",
    "cardContext": "期間未確認 · 熊本ヴォルターズ",
    "dataStatus": "master",
    "approvalId": "APP-AS002-20260921-01",
    "facts": [
      {
        "label": "英字表記",
        "value": "Tenyoku You",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B4W3S0008"
        ]
      },
      {
        "label": "生年月日",
        "value": "1988年10月6日",
        "context": "生年月日を掲載",
        "sourceIds": [
          "B4W3S0008"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000242",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "所属を公式資料で確認",
        "status": "master",
        "sourceIds": [
          "B4W3S0009"
        ]
      },
      {
        "id": "C000243",
        "period": "期間未確認",
        "organization": "東海大学",
        "organizationId": "ORG000015",
        "detail": "所属を公式資料で確認",
        "status": "master",
        "sourceIds": [
          "B4W3S0009"
        ]
      },
      {
        "id": "C000244",
        "period": "期間未確認",
        "organization": "三菱電機ダイヤモンドドルフィンズ",
        "organizationId": "ORG000104",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B4W3S0009"
        ]
      },
      {
        "id": "C000245",
        "period": "期間未確認",
        "organization": "名古屋ダイヤモンドドルフィンズ",
        "organizationId": "ORG000054",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B4W3S0009"
        ]
      },
      {
        "id": "C000246",
        "period": "期間未確認",
        "organization": "熊本ヴォルターズ",
        "organizationId": "ORG000067",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B4W3S0009"
        ]
      },
      {
        "id": "C000247",
        "period": "期間未確認",
        "organization": "新潟アルビレックスBB",
        "organizationId": "ORG000052",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B4W3S0009"
        ]
      },
      {
        "id": "C000248",
        "period": "期間未確認",
        "organization": "ライジングゼファー福岡",
        "organizationId": "ORG000040",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B4W3S0009"
        ]
      },
      {
        "id": "C000249",
        "period": "期間未確認",
        "organization": "東京サンレーヴス",
        "organizationId": "ORG000102",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B4W3S0009"
        ]
      },
      {
        "id": "C000250",
        "period": "期間未確認",
        "organization": "茨城ロボッツ",
        "organizationId": "ORG000103",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B4W3S0009"
        ]
      },
      {
        "id": "C000251",
        "period": "期間未確認",
        "organization": "茨城ロボッツ",
        "organizationId": "ORG000103",
        "detail": "Head Coach",
        "status": "master",
        "sourceIds": [
          "B4W3S0009"
        ]
      },
      {
        "id": "C000252",
        "period": "期間未確認",
        "organization": "熊本ヴォルターズ",
        "organizationId": "ORG000067",
        "detail": "Assistant Coach",
        "status": "master",
        "sourceIds": [
          "B4W3S0009"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000071",
    "slug": "p000071",
    "name": "今泉 太陽",
    "cardContext": "2022年〜 · 日本経済大学",
    "dataStatus": "master",
    "approvalId": "APP-AS002-20260921-01",
    "facts": [
      {
        "label": "生年月日",
        "value": "2003年8月12日",
        "context": "生年月日を掲載",
        "sourceIds": [
          "B4W4S0001"
        ]
      },
      {
        "label": "身長",
        "value": "181cm",
        "context": "ドラフト候補プロフィールの身長",
        "sourceIds": [
          "B4W4S0001"
        ]
      },
      {
        "label": "体重",
        "value": "74kg",
        "context": "ドラフト候補プロフィールの体重",
        "sourceIds": [
          "B4W4S0001"
        ]
      },
      {
        "label": "ポジション",
        "value": "SG",
        "context": "登録ポジション",
        "sourceIds": [
          "B4W4S0001"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000253",
        "period": "2019–2022年",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "所属を公式資料で確認",
        "status": "master",
        "sourceIds": [
          "B4W4S0001"
        ]
      },
      {
        "id": "C000254",
        "period": "2022年〜",
        "organization": "日本経済大学",
        "organizationId": "ORG000017",
        "detail": "選手 · 公式戦記録：2025インカレ 7試合",
        "status": "master",
        "sourceIds": [
          "B4W4S0002",
          "B4W4S0001"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000072",
    "slug": "p000072",
    "name": "崎濱 秀真",
    "cardContext": "2022年〜 · 新潟経営大学",
    "dataStatus": "master",
    "approvalId": "APP-AS002-20260921-01",
    "facts": [
      {
        "label": "生年月日",
        "value": "2003年8月21日",
        "context": "生年月日を掲載",
        "sourceIds": [
          "B4W4S0001"
        ]
      },
      {
        "label": "身長",
        "value": "181cm",
        "context": "ドラフト候補プロフィールの身長",
        "sourceIds": [
          "B4W4S0001"
        ]
      },
      {
        "label": "体重",
        "value": "83kg",
        "context": "ドラフト候補プロフィールの体重",
        "sourceIds": [
          "B4W4S0001"
        ]
      },
      {
        "label": "ポジション",
        "value": "PG/SG",
        "context": "登録ポジション",
        "sourceIds": [
          "B4W4S0001"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000255",
        "period": "2019–2022年",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "所属を公式資料で確認",
        "status": "master",
        "sourceIds": [
          "B4W4S0001"
        ]
      },
      {
        "id": "C000256",
        "period": "2022年〜",
        "organization": "新潟経営大学",
        "organizationId": "ORG000105",
        "detail": "選手 · 公式戦記録：2024インカレ 2試合",
        "status": "master",
        "sourceIds": [
          "B4W4S0003",
          "B4W4S0004",
          "B4W4S0001"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000073",
    "slug": "p000073",
    "name": "崎濱 秀斗",
    "cardContext": "2024年〜 · セントトーマス モア スクール",
    "dataStatus": "master",
    "approvalId": "APP-B005-20260921-01",
    "facts": [
      {
        "label": "英字表記",
        "value": "Shuto Sakihama",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B5W1S0002"
        ]
      },
      {
        "label": "生年月日",
        "value": "2005年5月8日",
        "context": "クラブ公式プロフィール",
        "sourceIds": [
          "B5W1S0001"
        ]
      },
      {
        "label": "身長",
        "value": "178cm",
        "context": "加入発表時の登録身長",
        "sourceIds": [
          "B5W1S0001"
        ]
      },
      {
        "label": "体重",
        "value": "84kg",
        "context": "加入発表時の登録体重",
        "sourceIds": [
          "B5W1S0001"
        ]
      },
      {
        "label": "ポジション",
        "value": "PG",
        "context": "加入発表時の登録ポジション",
        "sourceIds": [
          "B5W1S0001"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000257",
        "period": "2021–2024年",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B5W1S0001"
        ]
      },
      {
        "id": "C000258",
        "period": "2024年",
        "organization": "琉球ゴールデンキングスU18",
        "organizationId": "ORG000107",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B5W1S0001"
        ]
      },
      {
        "id": "C000259",
        "period": "2024年〜",
        "organization": "セントトーマス モア スクール",
        "organizationId": "ORG000108",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B5W1S0002",
          "B5W1S0001"
        ]
      },
      {
        "id": "C000260",
        "period": "2024–2026年",
        "organization": "琉球ゴールデンキングス",
        "organizationId": "ORG000106",
        "detail": "選手 · 登録区分：特別指定選手（プロ契約） · 公式戦記録：2024-25 B1 13試合・CS 4試合、2025-26 B1 40試合 · 活動状況：活動終了・退団",
        "status": "master",
        "sourceIds": [
          "B5W1S0001",
          "B5W1S0003",
          "B5W1S0002"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000074",
    "slug": "p000074",
    "name": "轟 琉維",
    "cardContext": "期間未確認 · 東海大学",
    "dataStatus": "master",
    "approvalId": "APP-B005-20260921-01",
    "facts": [
      {
        "label": "英字表記",
        "value": "Rui Todoroki",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B5W1S0008"
        ]
      },
      {
        "label": "生年月日",
        "value": "2004年5月1日",
        "context": "クラブ公式プロフィール",
        "sourceIds": [
          "B5W1S0004"
        ]
      },
      {
        "label": "身長",
        "value": "169cm",
        "context": "B.LEAGUE公式の登録身長",
        "sourceIds": [
          "B5W1S0008"
        ]
      },
      {
        "label": "体重",
        "value": "71kg",
        "context": "B.LEAGUE公式の登録体重",
        "sourceIds": [
          "B5W1S0008"
        ]
      },
      {
        "label": "ポジション",
        "value": "PG",
        "context": "クラブ公式の登録ポジション",
        "sourceIds": [
          "B5W1S0004"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000261",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "所属を公式資料で確認",
        "status": "master",
        "sourceIds": [
          "B5W1S0004"
        ]
      },
      {
        "id": "C000262",
        "period": "期間未確認",
        "organization": "東海大学",
        "organizationId": "ORG000015",
        "detail": "選手 · 学年：2年",
        "status": "master",
        "sourceIds": [
          "B5W1S0005",
          "B5W1S0004"
        ]
      },
      {
        "id": "C000263",
        "period": "2025年",
        "organization": "アルバルク東京",
        "organizationId": "ORG000109",
        "detail": "選手 · 登録区分：特別指定選手 · リーグ登録：2025-01-11登録完了 · 公式戦記録：2025-02-08 Bリーグ初出場・初得点 · 活動終了：2025-03-05",
        "status": "master",
        "sourceIds": [
          "B5W1S0004",
          "B5W1S0005",
          "B5W1S0006",
          "B5W1S0007"
        ]
      },
      {
        "id": "C000264",
        "period": "2025–2026年",
        "organization": "佐賀バルーナーズ",
        "organizationId": "ORG000048",
        "detail": "選手 · 公式戦記録：2025-26 B1 13試合",
        "status": "master",
        "sourceIds": [
          "B5W1S0008"
        ]
      }
    ],
    "aliases": []
  }
] as const;
