// Generated by scripts/build_site_master_data.py. Do not edit directly.
export const masterPublication = {
  "approvalId": "APP-B005-20260921-01",
  "approvedAt": "2026-09-21",
  "verifiedCommit": "7093141"
} as const;

export const masterSources = [
  {
    "id": "B5W1S0001",
    "title": "#17 崎濱秀斗選手加入（特別指定選手）のお知らせ",
    "publisher": "琉球ゴールデンキングス",
    "url": "https://goldenkings.jp/retired_numbers_26/detail_26/id=21221",
    "location": "選手プロフィール > 生年月日 / 選手プロフィール > 身長 / 選手プロフィール > 体重 / 選手プロフィール > ポジション / 選手プロフィール > 経歴 > 2021-24 / 選手プロフィール > 経歴 / 本文 > 福岡第一高校時代 / 選手プロフィール > 経歴 > 2024 / 本文 > キングスU18での活動経験 / 本文 > 学業とバスケットボール / 選手プロフィール > 経歴 > 2024- / 加入発表本文 / 発行元・加入発表本文 / 本文・選手プロフィール > 経歴",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0002",
    "title": "崎濱秀斗 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=51000486",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / 基本情報 > 出身校 / シーズン成績",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0003",
    "title": "#17 崎濱秀斗選手 特別指定選手の活動終了のご報告",
    "publisher": "琉球ゴールデンキングス",
    "url": "https://goldenkings.jp/clubkings/pages/id=25788",
    "location": "主な経歴 > 2024-26 / 発表本文",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0004",
    "title": "轟 琉維選手 2024-25シーズン 特別指定選手 加入のお知らせ",
    "publisher": "アルバルク東京",
    "url": "https://www.alvark-tokyo.jp/news/detail/team/id=19876",
    "location": "選手プロフィール > 生年月日 / 選手プロフィール > ポジション / 選手プロフィール > 出身校 / 本文 > 東海大学2年 / 加入発表本文 / 発表見出し・本文 / 発行元・加入発表本文 / 公開日・加入発表本文",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0005",
    "title": "#8 轟 琉維選手 リーグ登録完了のお知らせ",
    "publisher": "アルバルク東京",
    "url": "https://www.alvark-tokyo.jp/news/detail/event/team/media/id=19920",
    "location": "選手プロフィール > 出身校 / 発表本文",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0006",
    "title": "2/8（土）仙台89ERS戦 ゲームレポート",
    "publisher": "アルバルク東京",
    "url": "https://www.alvark-tokyo.jp/news/detail/game/id=250208",
    "location": "ゲームレポート冒頭",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0007",
    "title": "轟 琉維選手 2024-25シーズン 特別指定選手 活動終了のご報告",
    "publisher": "アルバルク東京",
    "url": "https://www.alvark-tokyo.jp/news/detail/team/id=20126",
    "location": "発表本文 / 活動終了本文 > 2025年3月5日",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0008",
    "title": "轟琉維 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=51000457",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / 基本情報 > 身長 / 基本情報 > 体重 / クラブ所属履歴 > 2025-26 / シーズン成績 > 2025-26 B1 / シーズン成績・試合成績 / クラブ所属履歴 > 佐賀 / クラブ所属履歴 > 2025-26 佐賀",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0009",
    "title": "佐藤涼成選手 2024-25シーズン 特別指定選手登録のお知らせ",
    "publisher": "横浜ビー・コルセアーズ",
    "url": "https://b-corsairs.com/news/team_20241221_1/",
    "location": "登録発表本文 / 発表見出し・本文 / 登録発表 > 活動期間 / 発行元・登録発表本文 / 活動期間 > 2025年1月1日 / 活動期間 > 2025年3月5日",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0010",
    "title": "佐藤涼成 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=51000447",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / シーズン成績",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0011",
    "title": "#88 佐藤 涼成選手 契約合意（新規）のお知らせ",
    "publisher": "広島ドラゴンフライズ",
    "url": "https://hiroshimadragonflies.com/news/detail/id=21158",
    "location": "選手プロフィール > 生年月日 / 契約発表本文 / 経歴 > 2025年- / 選手プロフィール > 出身校 / 発行元・契約発表本文",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0012",
    "title": "2026-27シーズン 契約合意（継続）選手のお知らせ",
    "publisher": "広島ドラゴンフライズ",
    "url": "https://hiroshimadragonflies.com/news/detail/id=24483",
    "location": "佐藤涼成 > GMコメント",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0013",
    "title": "河合瑠那選手 特別指定選手登録のお知らせ",
    "publisher": "横浜エクセレンス",
    "url": "https://yokohama-ex.jp/team/pages/id=22814",
    "location": "登録発表本文 / 発表見出し・本文 / 特別指定選手登録発表",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0014",
    "title": "河合瑠那 B.LEAGUE公式選手プロフィール",
    "publisher": "B.LEAGUE",
    "url": "https://www.bleague.jp/roster_detail/?PlayerID=51000607",
    "location": "基本情報 > 選手名 / 基本情報 > 英語表記 / シーズン成績 > 2025-26 B2 / シーズン成績",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  },
  {
    "id": "B5W1S0015",
    "title": "河合瑠那 選手 特別指定選手活動終了のお知らせ",
    "publisher": "横浜エクセレンス",
    "url": "https://yokohama-ex.jp/news/detail/id=25440",
    "location": "公開日・発表本文 / 発表本文 / 発行元・活動終了本文 / 2025-26シーズンをもって活動終了",
    "accessedAt": "2026-09-21",
    "dataStatus": "master"
  }
] as const;

export const masterPlayers = [
  {
    "id": "P000028",
    "slug": "p000028",
    "name": "佐藤 涼成",
    "cardContext": "2025年〜 · 広島ドラゴンフライズ",
    "dataStatus": "master",
    "approvalId": "APP-B005-20260921-01",
    "facts": [
      {
        "label": "英字表記",
        "value": "Ryosei Sato",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B5W1S0010"
        ]
      },
      {
        "label": "生年月日",
        "value": "2003年7月9日",
        "context": "クラブ公式プロフィール",
        "sourceIds": [
          "B5W1S0011"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000265",
        "period": "2025年",
        "organization": "横浜ビー・コルセアーズ",
        "organizationId": "ORG000055",
        "detail": "選手 · 登録区分：特別指定選手 · 公式戦記録：2024-25 B1 7試合 · 活動期間：2025-01-01〜2025-03-05",
        "status": "master",
        "sourceIds": [
          "B5W1S0009",
          "B5W1S0010"
        ]
      },
      {
        "id": "C000266",
        "period": "2025年〜",
        "organization": "広島ドラゴンフライズ",
        "organizationId": "ORG000110",
        "detail": "選手 · 契約区分：特別指定選手（プロ契約） · 公式戦記録：2025-26 B1 25試合 · 契約継続：2026-27以降の複数年契約",
        "status": "master",
        "sourceIds": [
          "B5W1S0011",
          "B5W1S0010",
          "B5W1S0012"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000066",
    "slug": "p000066",
    "name": "河合 瑠那",
    "cardContext": "2026年 · 横浜エクセレンス",
    "dataStatus": "master",
    "approvalId": "APP-B005-20260921-01",
    "facts": [
      {
        "label": "英字表記",
        "value": "Runa Kawai",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B5W1S0014"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000229",
        "period": "2026年",
        "organization": "横浜エクセレンス",
        "organizationId": "ORG000090",
        "detail": "選手 · 登録区分：特別指定選手 · 公式戦記録：2025-26 B2 1試合3分33秒・2得点 · 活動終了発表：2026-05-21 · 自由交渉選手リスト発表：2026-05-21",
        "status": "master",
        "sourceIds": [
          "B5W1S0013",
          "B5W1S0014",
          "B5W1S0015"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000073",
    "slug": "p000073",
    "name": "崎濱 秀斗",
    "cardContext": "2024年〜 · セントトーマス モア スクール",
    "dataStatus": "master",
    "approvalId": "APP-B005-20260921-01",
    "facts": [
      {
        "label": "英字表記",
        "value": "Shuto Sakihama",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B5W1S0002"
        ]
      },
      {
        "label": "生年月日",
        "value": "2005年5月8日",
        "context": "クラブ公式プロフィール",
        "sourceIds": [
          "B5W1S0001"
        ]
      },
      {
        "label": "身長",
        "value": "178cm",
        "context": "加入発表時の登録身長",
        "sourceIds": [
          "B5W1S0001"
        ]
      },
      {
        "label": "体重",
        "value": "84kg",
        "context": "加入発表時の登録体重",
        "sourceIds": [
          "B5W1S0001"
        ]
      },
      {
        "label": "ポジション",
        "value": "PG",
        "context": "加入発表時の登録ポジション",
        "sourceIds": [
          "B5W1S0001"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000257",
        "period": "2021–2024年",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B5W1S0001"
        ]
      },
      {
        "id": "C000258",
        "period": "2024年",
        "organization": "琉球ゴールデンキングスU18",
        "organizationId": "ORG000107",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B5W1S0001"
        ]
      },
      {
        "id": "C000259",
        "period": "2024年〜",
        "organization": "セントトーマス モア スクール",
        "organizationId": "ORG000108",
        "detail": "選手",
        "status": "master",
        "sourceIds": [
          "B5W1S0002",
          "B5W1S0001"
        ]
      },
      {
        "id": "C000260",
        "period": "2024–2026年",
        "organization": "琉球ゴールデンキングス",
        "organizationId": "ORG000106",
        "detail": "選手 · 登録区分：特別指定選手（プロ契約） · 公式戦記録：2024-25 B1 13試合・CS 4試合、2025-26 B1 40試合 · 活動状況：活動終了・退団",
        "status": "master",
        "sourceIds": [
          "B5W1S0001",
          "B5W1S0003",
          "B5W1S0002"
        ]
      }
    ],
    "aliases": []
  },
  {
    "id": "P000074",
    "slug": "p000074",
    "name": "轟 琉維",
    "cardContext": "期間未確認 · 東海大学",
    "dataStatus": "master",
    "approvalId": "APP-B005-20260921-01",
    "facts": [
      {
        "label": "英字表記",
        "value": "Rui Todoroki",
        "context": "B.LEAGUE公式の英語表記",
        "sourceIds": [
          "B5W1S0008"
        ]
      },
      {
        "label": "生年月日",
        "value": "2004年5月1日",
        "context": "クラブ公式プロフィール",
        "sourceIds": [
          "B5W1S0004"
        ]
      },
      {
        "label": "身長",
        "value": "169cm",
        "context": "B.LEAGUE公式の登録身長",
        "sourceIds": [
          "B5W1S0008"
        ]
      },
      {
        "label": "体重",
        "value": "71kg",
        "context": "B.LEAGUE公式の登録体重",
        "sourceIds": [
          "B5W1S0008"
        ]
      },
      {
        "label": "ポジション",
        "value": "PG",
        "context": "クラブ公式の登録ポジション",
        "sourceIds": [
          "B5W1S0004"
        ]
      }
    ],
    "careers": [
      {
        "id": "C000261",
        "period": "期間未確認",
        "organization": "福岡第一高等学校",
        "organizationId": "ORG000010",
        "detail": "所属を公式資料で確認",
        "status": "master",
        "sourceIds": [
          "B5W1S0004"
        ]
      },
      {
        "id": "C000262",
        "period": "期間未確認",
        "organization": "東海大学",
        "organizationId": "ORG000015",
        "detail": "選手 · 学年：2年",
        "status": "master",
        "sourceIds": [
          "B5W1S0005",
          "B5W1S0004"
        ]
      },
      {
        "id": "C000263",
        "period": "2025年",
        "organization": "アルバルク東京",
        "organizationId": "ORG000109",
        "detail": "選手 · 登録区分：特別指定選手 · リーグ登録：2025-01-11登録完了 · 公式戦記録：2025-02-08 Bリーグ初出場・初得点 · 活動終了：2025-03-05",
        "status": "master",
        "sourceIds": [
          "B5W1S0004",
          "B5W1S0005",
          "B5W1S0006",
          "B5W1S0007"
        ]
      },
      {
        "id": "C000264",
        "period": "2025–2026年",
        "organization": "佐賀バルーナーズ",
        "organizationId": "ORG000048",
        "detail": "選手 · 公式戦記録：2025-26 B1 13試合",
        "status": "master",
        "sourceIds": [
          "B5W1S0008"
        ]
      }
    ],
    "aliases": []
  }
] as const;
