export const sources = [
  {
    id: 'SRC000010',
    title: '福岡県代表 男子 福岡第一高等学校 — 選手名鑑 2020',
    publisher: 'J SPORTS',
    url: 'https://www.jsports.co.jp/basketball/wintercup/players_2020/m_fukuoka/',
    location: '選手情報のNO・氏名・POS欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'SRC000014',
    title: '福岡第一高校 — 第96回天皇杯 出場チーム',
    publisher: '日本バスケットボール協会（JBA）',
    url: 'https://zennihon2020-21.japanbasketball.jp/team/1st/men-fukuoka',
    location: 'プレイヤー一覧・チームスタッフ欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'SRC000015',
    title: 'バスケSOARERS CUP2023開催',
    publisher: '専修大学',
    url: 'https://www.senshu-u.ac.jp/news/nid00020088.html',
    location: '本文・写真説明「當山修梧さん（経済3）」',
    accessedAt: '2026-09-13',
  },
  {
    id: 'SRC000016',
    title: 'ハーパー・ジャン・ローレンス・ジュニア選手 加入のお知らせ',
    publisher: 'サンロッカーズ渋谷',
    url: 'https://www.sunrockers.jp/news/detail/id=18442',
    location: '出身校・経歴欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'SRC000017',
    title: 'ジャン・ローレンス・ハーパージュニア選手 契約締結および登録名変更のお知らせ',
    publisher: 'サンロッカーズ渋谷',
    url: 'https://www.sunrockers.jp/news/detail/id=19031',
    location: '登録名変更前・変更後、経歴欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'SRC000018',
    title: 'SoftBank ウインターカップ2021 — 福岡第一 試合公式記録',
    publisher: '日本バスケットボール協会（JBA）',
    url: 'https://jba-cs.japanbasketball.jp/jba-sitedata/wintercup/2021/official/156.pdf',
    location: '福岡第一の選手名・背番号欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'SRC000019',
    title: '福岡第一高等学校 2022学校案内',
    publisher: '福岡第一高等学校',
    url: 'https://f.f-parama.ed.jp/wp-content/uploads/2021/06/panflet2022.pdf',
    location: '男子バスケットボール部紹介欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'SRC000020',
    title: '佐藤涼成選手が「B.LEAGUE UNITED」に選出',
    publisher: '白鴎大学男子バスケットボール部',
    url: 'https://sports.hakuoh.jp/basketball-m/archives/1117',
    location: '選手紹介・出身校欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'SRC000021',
    title: '福岡県代表 男子 福岡第一高等学校 — 選手名鑑 2021',
    publisher: 'J SPORTS',
    url: 'https://www.jsports.co.jp/basketball/wintercup/players_2021/m_9/',
    location: '選手情報の氏名・学年・POS・身長欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'SRC000022',
    title: '第74回全日本大学バスケットボール選手権大会 — 日本体育大学',
    publisher: '全日本大学バスケットボール連盟',
    url: 'https://jubf.jp/game/university-detail/id/5/type/intercollege/y/2022/s/men',
    location: 'ROSTER 早田流星欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'SRC000023',
    title: '2019年度 バスケットボール男子U16日本代表チーム 日本代表候補選手',
    publisher: '日本バスケットボール協会（JBA）',
    url: 'https://www.japanbasketball.jp/wp-content/uploads/U16-japan_men_member_20190415.pdf',
    location: '鷹野祐磨の氏名・英字表記・学年・ポジション欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'SRC000024',
    title: '福岡第一高校 — 第95回天皇杯 出場チーム',
    publisher: '日本バスケットボール協会（JBA）',
    url: 'https://zennihon2019-20.japanbasketball.jp/team/2nd/m_fukuoka',
    location: 'チームスタッフ欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'SRC000025',
    title: '第62回関東大学バスケットボール新人戦 ご案内',
    publisher: '青山学院大学男子バスケットボール部',
    url: 'https://agu-basketball.com/news/detail/id/18951',
    location: 'メンバー 星賀舞也欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'SRC000026',
    title: '第77回全日本大学バスケットボール選手権大会 — 九州国際大学',
    publisher: '全日本大学バスケットボール連盟',
    url: 'https://jubf.jp/game/university-detail/id/230/type/intercollege/y/2025/s/men',
    location: 'ROSTER 岡本汰稀欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'SRC000027',
    title: '第74回全日本大学バスケットボール選手権大会 — 東海大学九州',
    publisher: '全日本大学バスケットボール連盟',
    url: 'https://jubf.jp/game/university-detail/id/12/type/intercollege/y/2022/s/men',
    location: 'ROSTER 岩下周介欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'SRC000028',
    title: '第98回関東大学バスケットボールリーグ戦 試合記録',
    publisher: '関東大学バスケットボール連盟',
    url: 'https://www.kcbbf.jp/game/detail/id/13912',
    location: '山梨学院大学 #70 選手欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'SRC000029',
    title: '第77回全日本大学バスケットボール選手権大会 — 山梨学院大学',
    publisher: '全日本大学バスケットボール連盟',
    url: 'https://jubf.jp/game/university-detail/id/204/type/intercollege/y/2025/s/men',
    location: 'ROSTER #70 カマレムレマ フランシス欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'BLC-P001',
    title: '2026-27シーズン 鵤誠司選手 契約発表',
    publisher: '宇都宮ブレックス',
    url: 'https://www.utsunomiyabrex.com/contract/2026-27_18/',
    location: '契約・選手プロフィール・経歴欄',
    accessedAt: '2026-09-14',
  },
  {
    id: 'BLC-H001',
    title: '男子U18日本代表候補選手',
    publisher: '日本バスケットボール協会（JBA）',
    url: 'https://japanbasketball.jp/event/news_detail-php-news_id=1029.html',
    location: '鵤誠司の所属・学年欄',
    accessedAt: '2026-09-14',
  },
  {
    id: 'BLC-U001',
    title: '2012年度 男子U18日本代表候補選手名簿',
    publisher: '日本バスケットボール協会（JBA）',
    url: 'https://www.japanbasketball.jp/wp/wp-content/uploads/jba2012163.pdf',
    location: '鵤誠司の大学・学年欄',
    accessedAt: '2026-09-14',
  },
  {
    id: 'BLC-P002',
    title: '内尾聡理 選手プロフィール',
    publisher: '佐賀バルーナーズ',
    url: 'https://ballooners.jp/team/players/detail/id=48332?PlayerID=51000353',
    location: '選手プロフィール・所属欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'BLC-H002',
    title: '福岡第一高校 — 第95回天皇杯 出場チーム',
    publisher: '日本バスケットボール協会（JBA）',
    url: 'https://zennihon2019-20.japanbasketball.jp/team/2nd/m_fukuoka',
    location: '内尾聡理の選手欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'BLC-U002',
    title: '2021年度 男子U22日本代表候補選手名簿',
    publisher: '日本バスケットボール協会（JBA）',
    url: 'https://www.japanbasketball.jp/wp-content/uploads/member_U22WUG2022_Camp_20220220.pdf',
    location: '内尾聡理の大学・学年欄',
    accessedAt: '2026-09-14',
  },
  {
    id: 'BLC-P003',
    title: '神田壮一郎 選手情報',
    publisher: 'B.LEAGUE',
    url: 'https://www.bleague.jp/roster_detail/?PlayerID=51000380',
    location: '選手プロフィール・所属欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'BLC-H003',
    title: '拓殖大学 学報392号',
    publisher: '拓殖大学',
    url: 'https://www.takushoku-u.ac.jp/files/gakuhou_392.pdf',
    location: '神田壮一郎の出身校・進路欄',
    accessedAt: '2026-09-14',
  },
  {
    id: 'BLC-U003',
    title: '拓殖大学 学報392号',
    publisher: '拓殖大学',
    url: 'https://www.takushoku-u.ac.jp/files/gakuhou_392.pdf',
    location: '神田壮一郎の学年・主将欄',
    accessedAt: '2026-09-14',
  },
  {
    id: 'BLC-P004',
    title: '2026-27シーズン 井手拓実選手 契約発表',
    publisher: 'アースフレンズ東京Z',
    url: 'https://eftokyo-z.jp/news/260702-1',
    location: '選手プロフィール・経歴欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'BLC-H004',
    title: '2026-27シーズン 井手拓実選手 契約発表',
    publisher: 'アースフレンズ東京Z',
    url: 'https://eftokyo-z.jp/news/260702-1',
    location: '福岡第一高校の経歴欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'BLC-U004',
    title: '井手拓実選手 2021-22シーズン契約発表',
    publisher: '広島ドラゴンフライズ',
    url: 'https://hiroshimadragonflies.com/news/detail/id=16585',
    location: '日本体育大学4年・選手プロフィール欄',
    accessedAt: '2026-09-14',
  },
  {
    id: 'BLC-P005',
    title: '2026-27シーズン 並里成選手 契約発表',
    publisher: '横浜ビー・コルセアーズ',
    url: 'https://b-corsairs.com/news/team_20260519_0/',
    location: '選手プロフィール・経歴欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'BLC-H005',
    title: '2026-27シーズン 並里成選手 契約発表',
    publisher: '横浜ビー・コルセアーズ',
    url: 'https://b-corsairs.com/news/team_20260519_0/',
    location: '福岡第一高校の経歴欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'BLC-U005',
    title: '2026-27シーズン 並里成選手 契約発表',
    publisher: '横浜ビー・コルセアーズ',
    url: 'https://b-corsairs.com/news/team_20260519_0/',
    location: 'South Kent School・プロ経歴欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'BLC-P006',
    title: '2026-27シーズン 狩野祐介選手 契約発表',
    publisher: 'ライジングゼファー福岡',
    url: 'https://r-zephyr.com/news/detail/id=21959',
    location: '選手プロフィール・経歴欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'BLC-H006',
    title: '試合情報・選手紹介',
    publisher: 'ライジングゼファー福岡',
    url: 'https://r-zephyr.com/news/game_20251015/',
    location: '狩野祐介の福岡第一高校経歴欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'BLC-U006',
    title: 'JBA公式広報誌 the Backboard Vol.1',
    publisher: '日本バスケットボール協会（JBA）',
    url: 'https://www.japanbasketball.jp/wp/wp-content/uploads/theBackboard_vol.001.pdf',
    location: '2012年度インカレ 狩野祐介の学年欄',
    accessedAt: '2026-09-14',
  },
  {
    id: 'BLC-P007',
    title: '2026-27シーズン 小川麻斗選手 加入発表',
    publisher: '神戸ストークス',
    url: 'https://www.storks.jp/news/detail/id=21839',
    location: '選手プロフィール・経歴欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'BLC-H007',
    title: 'ウインターカップ2019 大会結果',
    publisher: '日本バスケットボール協会（JBA）',
    url: 'https://u18.japanbasketball.jp/convention-news/234/',
    location: '男子ベストファイブ #46 小川麻斗',
    accessedAt: '2026-09-13',
  },
  {
    id: 'BLC-U007',
    title: '2022-23シーズン 小川麻斗選手 新加入のお知らせ',
    publisher: '千葉ジェッツ',
    url: 'https://chibajets.jp/news/detail/id=21415',
    location: '日本体育大学在学・男子部退部・本契約欄',
    accessedAt: '2026-09-14',
  },
  {
    id: 'BLC-P008',
    title: '2026-27シーズン 渡辺竜之佑選手 契約発表',
    publisher: '京都ハンナリーズ',
    url: 'https://hannaryz.jp/news/detail/id=24508',
    location: '選手プロフィール・経歴欄',
    accessedAt: '2026-09-13',
  },
  {
    id: 'BLC-H008',
    title: '男子U18日本代表候補選手',
    publisher: '日本バスケットボール協会（JBA）',
    url: 'https://japanbasketball.jp/event/news_detail-php-news_id=1029.html',
    location: '渡辺竜之佑の所属・学年欄',
    accessedAt: '2026-09-14',
  },
  {
    id: 'BLC-U008',
    title: '専修大学広報 2013年4月号',
    publisher: '専修大学',
    url: 'https://www.senshu-u.ac.jp/albums/abm.php?d=2119&f=abm00004493.pdf&n=2013%E5%B9%B44%E6%9C%88%E5%8F%B7%EF%BC%88%E7%AC%AC511%E5%8F%B7%EF%BC%8914%E9%9D%A2.pdf',
    location: '男子バスケットボール部 新入生紹介欄',
    accessedAt: '2026-09-14',
  },
] as const;

export const players = [
  {
    id: 'P000010',
    slug: 'shugo-toyama',
    name: '當山 修梧',
    cardContext: '2020年 · 選手',
    facts: [
      { label: '役割', value: '選手', context: '2020年・第96回天皇杯', sourceIds: ['SRC000014'] },
      { label: '背番号', value: '#1', context: '2020年・第96回天皇杯', sourceIds: ['SRC000014'] },
      { label: 'ポジション', value: 'PG', context: '2020年・ウインターカップ選手名鑑', sourceIds: ['SRC000010'] },
    ],
    careers: [
      { period: '2020年', organization: '福岡第一高等学校', detail: '第96回天皇杯 登録選手', status: 'candidate', sourceIds: ['SRC000014'] },
      { period: '2023年確認', organization: '専修大学', detail: '大学公式記事で男子バスケットボール部での活動を確認', status: 'candidate', sourceIds: ['SRC000015'] },
    ],
    aliases: [],
  },
  {
    id: 'P000011',
    slug: 'ryuyu-sunakawa',
    name: '砂川 琉勇',
    cardContext: '2020年 · 選手',
    facts: [
      { label: '役割', value: '選手', context: '2020年・第96回天皇杯', sourceIds: ['SRC000014'] },
      { label: '背番号', value: '#23', context: '2020年・第96回天皇杯', sourceIds: ['SRC000014'] },
      { label: 'ポジション', value: 'SG', context: '2020年・ウインターカップ選手名鑑', sourceIds: ['SRC000010'] },
    ],
    careers: [
      { period: '2020年', organization: '福岡第一高等学校', detail: '第96回天皇杯 登録選手', status: 'candidate', sourceIds: ['SRC000014'] },
      { period: '卒業後', organization: null, detail: '進路先は確認中', status: 'hold', sourceIds: [] },
    ],
    aliases: [],
  },
  {
    id: 'P000012',
    slug: 'john-lawrence-harper-jr',
    name: 'ハーパー ジャン ローレンス ジュニア',
    cardContext: '2020年 · 選手',
    facts: [
      { label: '役割', value: '選手', context: '2020年・第96回天皇杯', sourceIds: ['SRC000014'] },
      { label: '背番号', value: '#31', context: '2020年・第96回天皇杯', sourceIds: ['SRC000014'] },
      { label: 'ポジション', value: 'PG', context: '2020年・ウインターカップ選手名鑑', sourceIds: ['SRC000010'] },
    ],
    careers: [
      { period: '2020年', organization: '福岡第一高等学校', detail: '第96回天皇杯 登録選手', status: 'candidate', sourceIds: ['SRC000014'] },
      { period: '高校卒業後', organization: '東海大学', detail: 'サンロッカーズ渋谷公式発表の出身校・経歴欄で確認', status: 'candidate', sourceIds: ['SRC000016'] },
      { period: '2020-21〜2023-24', organization: 'B.LEAGUE 特別指定選手', detail: '琉球、群馬、サンロッカーズ渋谷での登録歴', status: 'candidate', sourceIds: ['SRC000016', 'SRC000017'] },
      { period: '2024年〜', organization: 'サンロッカーズ渋谷', detail: '2024-25加入、2025-26契約を公式発表で確認', status: 'candidate', sourceIds: ['SRC000016', 'SRC000017'] },
    ],
    aliases: [
      { period: '2025-26', label: '登録名変更', value: 'ジャン・ローレンス・ハーパージュニア', sourceIds: ['SRC000017'] },
    ],
  },
  {
    id: 'P000017',
    slug: 'p000017',
    name: '泉美 優知',
    cardContext: '2020年 · マネージャー',
    facts: [
      { label: '役割', value: 'Manager', context: '2020年・第96回天皇杯', sourceIds: ['SRC000014'] },
    ],
    careers: [
      { period: '2020年', organization: '福岡第一高等学校', detail: '第96回天皇杯 チームスタッフ', status: 'candidate', sourceIds: ['SRC000014'] },
      { period: '卒業後', organization: null, detail: '進路先と役割は確認中', status: 'hold', sourceIds: [] },
    ],
    aliases: [],
  },
  {
    id: 'P000028',
    slug: 'p000028',
    name: '佐藤 涼成',
    cardContext: '2021年 · 選手',
    facts: [
      { label: '役割', value: '選手', context: '2021年・ウインターカップ', sourceIds: ['SRC000018'] },
      { label: '背番号', value: '#88', context: '2021年・ウインターカップ', sourceIds: ['SRC000018'] },
      { label: 'チーム内役割', value: 'ゲームキャプテン', context: '2021年', sourceIds: ['SRC000019'] },
    ],
    careers: [
      { period: '2021年', organization: '福岡第一高等学校', detail: 'ウインターカップ 登録選手', status: 'candidate', sourceIds: ['SRC000018'] },
      { period: '高校卒業後', organization: '白鴎大学', detail: '大学公式記事で男子バスケットボール部での活動を確認', status: 'candidate', sourceIds: ['SRC000020'] },
    ],
    aliases: [],
  },
  {
    id: 'P000029',
    slug: 'p000029',
    name: '早田 流星',
    cardContext: '2021年 · 選手',
    facts: [
      { label: '役割', value: '選手', context: '2021年・ウインターカップ', sourceIds: ['SRC000021'] },
      { label: '背番号', value: '#10', context: '2021年・ウインターカップ', sourceIds: ['SRC000021'] },
      { label: 'チーム内役割', value: 'チームキャプテン', context: '2021年', sourceIds: ['SRC000019'] },
    ],
    careers: [
      { period: '2021年', organization: '福岡第一高等学校', detail: 'ウインターカップ 登録選手', status: 'candidate', sourceIds: ['SRC000021'] },
      { period: '2022年', organization: '日本体育大学', detail: '1年・#10・F・185cm', status: 'candidate', sourceIds: ['SRC000022'] },
    ],
    aliases: [],
  },
  {
    id: 'P000030',
    slug: 'p000030',
    name: '鷹野 祐磨',
    cardContext: '2021年 · 選手',
    facts: [
      { label: '学年', value: '1年', context: '2019年・U16日本代表候補', sourceIds: ['SRC000023'] },
      { label: 'ポジション', value: 'SF', context: '2019年・U16日本代表候補', sourceIds: ['SRC000023'] },
      { label: '英字表記', value: 'TAKANO, Yuma', context: '2019年・JBA資料', sourceIds: ['SRC000023'] },
      { label: '背番号', value: '#14', context: '2021年・ウインターカップ', sourceIds: ['SRC000018'] },
    ],
    careers: [
      { period: '2019年', organization: '福岡第一高等学校', detail: 'U16日本代表候補資料で1年として確認', status: 'candidate', sourceIds: ['SRC000023'] },
      { period: '2021年', organization: '福岡第一高等学校', detail: 'ウインターカップ #14', status: 'candidate', sourceIds: ['SRC000018'] },
    ],
    aliases: [],
  },
  {
    id: 'P000031',
    slug: 'p000031',
    name: '星賀 舞也',
    cardContext: '2020年 · 選手',
    facts: [
      { label: '役割', value: '選手', context: '2020年・第96回天皇杯', sourceIds: ['SRC000014'] },
      { label: '背番号', value: '#24', context: '2020年・第96回天皇杯', sourceIds: ['SRC000014'] },
      { label: '身長', value: '190cm', context: '2020年・第96回天皇杯', sourceIds: ['SRC000014'] },
    ],
    careers: [
      { period: '2019年', organization: '福岡第一高等学校', detail: '第95回天皇杯 Analyst', status: 'candidate', sourceIds: ['SRC000024'] },
      { period: '2020年', organization: '福岡第一高等学校', detail: '第96回天皇杯 登録選手・#24', status: 'candidate', sourceIds: ['SRC000014'] },
      { period: '2022年', organization: '青山学院大学', detail: '1年・#25', status: 'candidate', sourceIds: ['SRC000025'] },
    ],
    aliases: [],
  },
  {
    id: 'P000032',
    slug: 'p000032',
    name: '岡本 汰稀',
    cardContext: '2021年 · 選手',
    facts: [
      { label: '背番号', value: '#30', context: '2021年・ウインターカップ', sourceIds: ['SRC000018'] },
    ],
    careers: [
      { period: '2021年', organization: '福岡第一高等学校', detail: 'ウインターカップ #30', status: 'candidate', sourceIds: ['SRC000018'] },
      { period: '2025年確認', organization: '九州国際大学', detail: '大学大会登録 #23', status: 'candidate', sourceIds: ['SRC000026'] },
    ],
    aliases: [],
  },
  {
    id: 'P000033',
    slug: 'p000033',
    name: '岩下 周介',
    cardContext: '2021年 · 選手',
    facts: [
      { label: '背番号', value: '#68', context: '2021年・ウインターカップ', sourceIds: ['SRC000018'] },
    ],
    careers: [
      { period: '2021年', organization: '福岡第一高等学校', detail: 'ウインターカップ #68', status: 'candidate', sourceIds: ['SRC000018'] },
      { period: '2022年確認', organization: '東海大学九州', detail: '大学大会登録 #17', status: 'candidate', sourceIds: ['SRC000027'] },
    ],
    aliases: [],
  },
  {
    id: 'P000034',
    slug: 'p000034',
    name: 'カマレ ムレマ フランシス',
    cardContext: '2021年 · 選手',
    facts: [
      { label: '役割', value: '選手', context: '2021年・ウインターカップ', sourceIds: ['SRC000021'] },
      { label: '背番号', value: '#70', context: '2021年・ウインターカップ', sourceIds: ['SRC000021'] },
      { label: 'ポジション', value: 'C', context: '2021年・ウインターカップ', sourceIds: ['SRC000021'] },
      { label: '身長', value: '206cm', context: '2021年・ウインターカップ', sourceIds: ['SRC000021'] },
    ],
    careers: [
      { period: '2021年', organization: '福岡第一高等学校', detail: 'ウインターカップ 登録選手', status: 'candidate', sourceIds: ['SRC000021'] },
      { period: '2022～2025年確認', organization: '山梨学院大学', detail: '大学大会登録 #70', status: 'candidate', sourceIds: ['SRC000028', 'SRC000029'] },
    ],
    aliases: [],
  },
  {
    id: 'P000037',
    slug: 'p000037',
    name: '鵤 誠司',
    cardContext: '2026-27 · 宇都宮ブレックス',
    facts: [
      { label: '背番号', value: '#18', context: '2026-27シーズン', sourceIds: ['BLC-P001'] },
      { label: 'ポジション', value: 'PG', context: '2026-27シーズン', sourceIds: ['BLC-P001'] },
      { label: '身長・体重', value: '185cm・95kg', context: '2026-27シーズン', sourceIds: ['BLC-P001'] },
      { label: '生年月日', value: '1994年1月8日', context: '選手プロフィール', sourceIds: ['BLC-P001'] },
    ],
    careers: [
      { period: '2011年2月確認', organization: '福岡第一高等学校', detail: '高校2年として代表候補資料に掲載', status: 'candidate', sourceIds: ['BLC-H001'] },
      { period: '2013年3月確認', organization: '青山学院大学', detail: '大学1年として代表候補資料に掲載', status: 'candidate', sourceIds: ['BLC-U001'] },
      { period: '2015年', organization: '広島ドラゴンフライズ', detail: '公式経歴で加入を確認', status: 'candidate', sourceIds: ['BLC-P001'] },
      { period: '2017年〜', organization: '宇都宮ブレックス', detail: '2026-27シーズン契約を確認', status: 'candidate', sourceIds: ['BLC-P001'] },
    ],
    aliases: [],
  },
  {
    id: 'P000038',
    slug: 'p000038',
    name: '内尾 聡理',
    cardContext: '2026-27 · 佐賀バルーナーズ',
    facts: [
      { label: '背番号', value: '#18', context: '2026-27シーズン', sourceIds: ['BLC-P002'] },
      { label: 'ポジション', value: 'PG/SG', context: '2026-27シーズン', sourceIds: ['BLC-P002'] },
      { label: '身長・体重', value: '184cm・81kg', context: '2026-27シーズン', sourceIds: ['BLC-P002'] },
      { label: '生年月日', value: '2001年4月12日', context: '選手プロフィール', sourceIds: ['BLC-P002'] },
    ],
    careers: [
      { period: '2019年度', organization: '福岡第一高等学校', detail: '第95回天皇杯の登録選手', status: 'candidate', sourceIds: ['BLC-H002'] },
      { period: '2022年2月確認', organization: '中央大学', detail: '大学2年として代表候補資料に掲載', status: 'candidate', sourceIds: ['BLC-U002'] },
      { period: '2023-24', organization: '千葉ジェッツ', detail: '公式経歴で所属を確認', status: 'candidate', sourceIds: ['BLC-P002'] },
      { period: '2024-25', organization: 'ファイティングイーグルス名古屋', detail: '公式経歴で所属を確認', status: 'candidate', sourceIds: ['BLC-P002'] },
      { period: '2025年〜', organization: '佐賀バルーナーズ', detail: '2026-27シーズンの所属を確認', status: 'candidate', sourceIds: ['BLC-P002'] },
    ],
    aliases: [],
  },
  {
    id: 'P000040',
    slug: 'p000040',
    name: '神田 壮一郎',
    cardContext: '2026-27 · ウォルガ湘南',
    facts: [
      { label: '背番号', value: '#11', context: '2026-27シーズン', sourceIds: ['BLC-P003'] },
      { label: 'ポジション', value: 'SG/SF', context: '2026-27シーズン', sourceIds: ['BLC-P003'] },
      { label: '身長・体重', value: '190cm・90kg', context: '2026-27シーズン', sourceIds: ['BLC-P003'] },
      { label: '生年月日', value: '2001年6月16日', context: '選手プロフィール', sourceIds: ['BLC-P003'] },
    ],
    careers: [
      { period: '2019年度確認', organization: '福岡第一高等学校', detail: '大学公式資料の出身校欄で確認', status: 'candidate', sourceIds: ['BLC-H003'] },
      { period: '2023年度', organization: '拓殖大学', detail: '国際学科4年・男子バスケットボール部主将', status: 'candidate', sourceIds: ['BLC-U003'] },
      { period: '2024-26', organization: 'ファイティングイーグルス名古屋', detail: '公式選手情報の経歴欄で確認', status: 'candidate', sourceIds: ['BLC-P003'] },
      { period: '2026-27', organization: 'ウォルガ湘南', detail: 'リーグ公式選手情報で所属を確認', status: 'candidate', sourceIds: ['BLC-P003'] },
    ],
    aliases: [],
  },
  {
    id: 'P000036',
    slug: 'p000036',
    name: '井手 拓実',
    cardContext: '2026-27 · アースフレンズ東京Z',
    facts: [
      { label: '背番号', value: '#28', context: '2026-27シーズン', sourceIds: ['BLC-P004'] },
      { label: 'ポジション', value: 'PG', context: '2026-27シーズン', sourceIds: ['BLC-P004'] },
      { label: '身長・体重', value: '174cm・68kg', context: '2026-27契約発表', sourceIds: ['BLC-P004'] },
      { label: '生年月日', value: '1999年10月12日', context: '選手プロフィール', sourceIds: ['BLC-P004'] },
    ],
    careers: [
      { period: '2015-18', organization: '福岡第一高等学校', detail: 'クラブ公式経歴で確認', status: 'candidate', sourceIds: ['BLC-H004'] },
      { period: '2018-22', organization: '日本体育大学', detail: '2021年12月時点で4年', status: 'candidate', sourceIds: ['BLC-U004'] },
      { period: '2021-22', organization: '広島ドラゴンフライズ', detail: '大学在学中の本契約', status: 'candidate', sourceIds: ['BLC-U004'] },
      { period: '2026-27', organization: 'アースフレンズ東京Z', detail: '契約発表で所属を確認', status: 'candidate', sourceIds: ['BLC-P004'] },
    ],
    aliases: [],
  },
  {
    id: 'P000042',
    slug: 'p000042',
    name: '並里 成',
    cardContext: '2026-27 · 横浜ビー・コルセアーズ',
    facts: [
      { label: '背番号', value: '#33', context: '2026-27シーズン', sourceIds: ['BLC-P005'] },
      { label: 'ポジション', value: 'PG', context: '2026-27シーズン', sourceIds: ['BLC-P005'] },
      { label: '身長・体重', value: '172cm・72kg', context: '2026-27シーズン', sourceIds: ['BLC-P005'] },
      { label: '生年月日', value: '1989年8月7日', context: '選手プロフィール', sourceIds: ['BLC-P005'] },
    ],
    careers: [
      { period: '高校時代', organization: '福岡第一高等学校', detail: '公式経歴で在籍を確認。開始・終了年は表示保留', status: 'candidate', sourceIds: ['BLC-H005'] },
      { period: '2008-09', organization: 'South Kent School', detail: '公式経歴で確認', status: 'candidate', sourceIds: ['BLC-U005'] },
      { period: '2009-26', organization: 'B.LEAGUE等の国内クラブ', detail: '宇都宮、琉球、大阪、滋賀、群馬、FE名古屋での経歴', status: 'candidate', sourceIds: ['BLC-U005'] },
      { period: '2026-27', organization: '横浜ビー・コルセアーズ', detail: '契約発表で所属を確認', status: 'candidate', sourceIds: ['BLC-P005'] },
    ],
    aliases: [],
  },
  {
    id: 'P000041',
    slug: 'p000041',
    name: '狩野 祐介',
    cardContext: '2026-27 · ライジングゼファー福岡',
    facts: [
      { label: '背番号', value: '#32', context: '2026-27シーズン', sourceIds: ['BLC-P006'] },
      { label: 'ポジション', value: 'SG', context: '2026-27シーズン', sourceIds: ['BLC-P006'] },
      { label: '身長・体重', value: '184cm・83kg', context: '2026-27シーズン', sourceIds: ['BLC-P006'] },
      { label: '生年月日', value: '1990年4月18日', context: '選手プロフィール', sourceIds: ['BLC-P006'] },
    ],
    careers: [
      { period: '在籍時期未確認', organization: '福岡第一高等学校', detail: 'クラブ公式記事の経歴欄で確認', status: 'candidate', sourceIds: ['BLC-H006'] },
      { period: '2012年度', organization: '東海大学', detail: '大学4年としてインカレ登録を確認', status: 'candidate', sourceIds: ['BLC-U006'] },
      { period: '2013-25', organization: 'B.LEAGUE等の国内クラブ', detail: '東京EX、滋賀、名古屋D、佐賀での経歴', status: 'candidate', sourceIds: ['BLC-P006'] },
      { period: '2025年〜', organization: 'ライジングゼファー福岡', detail: '2026-27シーズン契約を確認', status: 'candidate', sourceIds: ['BLC-P006'] },
    ],
    aliases: [],
  },
  {
    id: 'P000035',
    slug: 'p000035',
    name: '小川 麻斗',
    cardContext: '2026-27 · 神戸ストークス',
    facts: [
      { label: '背番号', value: '#3', context: '2026-27シーズン', sourceIds: ['BLC-P007'] },
      { label: 'ポジション', value: 'PG', context: '2026-27シーズン', sourceIds: ['BLC-P007'] },
      { label: '身長・体重', value: '176cm・77kg', context: '2026-27シーズン', sourceIds: ['BLC-P007'] },
      { label: '生年月日', value: '2001年8月23日', context: '選手プロフィール', sourceIds: ['BLC-P007'] },
    ],
    careers: [
      { period: '2019年度', organization: '福岡第一高等学校', detail: '3年・#46。大会ベストファイブ', status: 'candidate', sourceIds: ['BLC-H007'] },
      { period: '2022年12月確認', organization: '日本体育大学', detail: '在学を継続し、男子バスケットボール部を退部', status: 'candidate', sourceIds: ['BLC-U007'] },
      { period: '2022年12月〜', organization: '千葉ジェッツ', detail: 'プロ契約を確認', status: 'candidate', sourceIds: ['BLC-U007'] },
      { period: '2026-27', organization: '神戸ストークス', detail: '加入発表で所属を確認', status: 'candidate', sourceIds: ['BLC-P007'] },
    ],
    aliases: [],
  },
  {
    id: 'P000039',
    slug: 'p000039',
    name: '渡辺 竜之佑',
    cardContext: '2026-27 · 京都ハンナリーズ',
    facts: [
      { label: '背番号', value: '#16', context: '2026-27シーズン', sourceIds: ['BLC-P008'] },
      { label: 'ポジション', value: 'PG/SG', context: '2026-27シーズン', sourceIds: ['BLC-P008'] },
      { label: '身長・体重', value: '189cm・90kg', context: '2026-27シーズン', sourceIds: ['BLC-P008'] },
      { label: '生年月日', value: '1994年8月24日', context: '選手プロフィール', sourceIds: ['BLC-P008'] },
    ],
    careers: [
      { period: '2011年2月確認', organization: '福岡第一高等学校', detail: '高校1年として代表候補資料に掲載', status: 'candidate', sourceIds: ['BLC-H008'] },
      { period: '2013年4月', organization: '専修大学', detail: '大学公式広報の新入生紹介で確認', status: 'candidate', sourceIds: ['BLC-U008'] },
      { period: '2016年〜', organization: 'B.LEAGUE等の国内クラブ', detail: '琉球、新潟、SR渋谷、福井での経歴', status: 'candidate', sourceIds: ['BLC-P008'] },
      { period: '2026-27', organization: '京都ハンナリーズ', detail: '契約発表で所属を確認', status: 'candidate', sourceIds: ['BLC-P008'] },
    ],
    aliases: [],
  },
] as const;

export function getPlayer(slug: string) {
  return players.find((player) => player.slug === slug);
}

export function getSources(ids: readonly string[]) {
  return sources.filter((source) => ids.includes(source.id));
}
